<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Communication/Notification+Framework/CreateMVAPushRecord" name="CreateMVAPushRecord-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Communication/Notification+Framework/CreateMVAPushRecord" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Communication/Notification+Framework/CreateMVAPushRecord" location="CreateMVAPushRecord.wsdl"/>
  <binding name="CreateMVAPushRecord_ptt-binding" type="tns:CreateMVAPushRecord_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="insert">
      <soap:operation soapAction="insert"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="CreateMVAPushRecord-service">
    <port name="CreateMVAPushRecord-port" binding="tns:CreateMVAPushRecord_ptt-binding">
      <soap:address location="jca://eis/DB/NOTIFICATION_DETAILS"/>
    </port>
  </service>
</definitions>