<?binding.jca CreateEmailRecord_db.jca?><wsdl:definitions name="CreateEmailRecord" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Communication/Notification+Framework/CreateEmailRecord" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Communication/Notification+Framework/CreateEmailRecord" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/CreateEmailRecord">
    <plt:partnerLinkType name="CreateEmailRecord_plt">
        <plt:role name="CreateEmailRecord_role">
            <plt:portType name="tns:CreateEmailRecord_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CreateEmailRecord" schemaLocation="../Schema/CreateEmailRecord_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="TbEmailDetailsCollection_msg">
        <wsdl:part name="TbEmailDetailsCollection" element="top:TbEmailDetailsCollection"/>
    </wsdl:message>
    <wsdl:portType name="CreateEmailRecord_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:TbEmailDetailsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>