<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Communication/Notification+Framework/CreateSMSRecord" name="CreateSMSRecord-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Communication/Notification+Framework/CreateSMSRecord" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Communication/Notification+Framework/CreateSMSRecord" location="CreateSMSRecord.wsdl"/>
  <binding name="CreateSMSRecord_ptt-binding" type="tns:CreateSMSRecord_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="insert">
      <soap:operation soapAction="insert"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="CreateSMSRecord-service">
    <port name="CreateSMSRecord-port" binding="tns:CreateSMSRecord_ptt-binding">
      <soap:address location="jca://eis/DB/NOTIFICATION_DETAILS"/>
    </port>
  </service>
</definitions>