<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Communication/Notification+Framework/GetMVAPushRecord" name="GetMVAPushRecord-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Communication/Notification+Framework/GetMVAPushRecord" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Communication/Notification+Framework/GetMVAPushRecord" location="GetMVAPushRecord.wsdl"/>
  <binding name="GetMVAPushRecord_ptt-binding" type="tns:GetMVAPushRecord_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="receive">
      <soap:operation soapAction="receive"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="GetMVAPushRecord-service">
    <port name="GetMVAPushRecord-port" binding="tns:GetMVAPushRecord_ptt-binding">
      <soap:address location="jca://eis/DB/NOTIFICATION_DETAILS"/>
    </port>
  </service>
</definitions>