<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Communication/Notification+Framework/GetNotificationDetails" name="GetNotificationDetails-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Communication/Notification+Framework/GetNotificationDetails" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Communication/Notification+Framework/GetNotificationDetails" location="GetNotificationDetails.wsdl"/>
  <binding name="GetNotificationDetails_ptt-binding" type="tns:GetNotificationDetails_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="GetNotificationDetails">
      <soap:operation soapAction="GetNotificationDetails"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="GetNotificationDetails-service">
    <port name="GetNotificationDetails-port" binding="tns:GetNotificationDetails_ptt-binding">
      <soap:address location="jca://eis/DB/VFQA_EGATE_CONFIG"/>
    </port>
  </service>
</definitions>