<?binding.jca GetSMSRecord_db.jca?><wsdl:definitions name="GetSMSRecord" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Communication/Notification+Framework/GetSMSRecord" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Communication/Notification+Framework/GetSMSRecord" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetSMSRecord">
    <plt:partnerLinkType name="GetSMSRecord_plt">
        <plt:role name="GetSMSRecord_role">
            <plt:portType name="tns:GetSMSRecord_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetSMSRecord" schemaLocation="../Schema/GetSMSRecord_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="TbSmsDetailsCollection_msg">
        <wsdl:part name="TbSmsDetailsCollection" element="top:TbSmsDetailsCollection"/>
    </wsdl:message>
    <wsdl:portType name="GetSMSRecord_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:TbSmsDetailsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>