<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Communication/Notification+Framework/UPDATE_STATUS" name="UPDATE_STATUS-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Communication/Notification+Framework/UPDATE_STATUS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Communication/Notification+Framework/UPDATE_STATUS" location="UPDATE_STATUS.wsdl"/>
  <binding name="UPDATE_STATUS_ptt-binding" type="tns:UPDATE_STATUS_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="UPDATE_STATUS">
      <soap:operation soapAction="UPDATE_STATUS"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="UPDATE_STATUS-service">
    <port name="UPDATE_STATUS-port" binding="tns:UPDATE_STATUS_ptt-binding">
      <soap:address location="jca://eis/DB/NOTIFICATION_DETAILS"/>
    </port>
  </service>
</definitions>