<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/AQ/SOADUMMYApplication/Project1/AQ_ENQUEUE" name="AQ_ENQUEUE-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/AQ/SOADUMMYApplication/Project1/AQ_ENQUEUE" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/AQ/SOADUMMYApplication/Project1/AQ_ENQUEUE" location="AQ_ENQUEUE.wsdl"/>
  <binding name="Enqueue_ptt-binding" type="tns:Enqueue_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="Enqueue">
      <soap:operation soapAction="Enqueue"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="AQ_ENQUEUE-service">
    <port name="AQ_ENQUEUE-port" binding="tns:Enqueue_ptt-binding">
      <soap:address location="jca://eis/AQ/PortalEventSyncAQ1"/>
    </port>
  </service>
</definitions>