--    Copyright (c) 2005 BEA Systems, Inc.
--    All rights reserved
--
--    THIS IS UNPUBLISHED PROPRIETARY
--    SOURCE CODE OF BEA Systems, Inc.
--    The copyright notice above does not
--    evidence any actual or intended
--    publication of such source code.


-- WLI_QS_REPORT_ATTRIBUTE

CREATE TABLE WLI_QS_REPORT_ATTRIBUTE (
	MSG_GUID 		VARCHAR2(64) 	NOT NULL,
	DB_TIMESTAMP 		DATE 		DEFAULT  SYSDATE NOT NULL,
	LOCALHOST_TIMESTAMP 	DATE 		NOT NULL,
	HOST_NAME 		VARCHAR2(50) 	NOT NULL,
	STATE           VARCHAR(8)      NOT NULL,
	NODE 		    VARCHAR(128) 	NULL,
	PIPELINE_NAME 		VARCHAR2(128) 	NULL,
	STAGE_NAME 		VARCHAR2(128) 	NULL,
	INBOUND_SERVICE_NAME 	VARCHAR2(256) 	NOT NULL,
	INBOUND_SERVICE_URI 	VARCHAR2(128) 	NOT NULL,	
	INBOUND_OPERATION 	VARCHAR2(64) 	NULL,	
	OUTBOUND_SERVICE_NAME 	VARCHAR2(256)	NULL,
	OUTBOUND_SERVICE_URI 	VARCHAR2(256) 	NULL,	
	OUTBOUND_OPERATION 	VARCHAR2(64)	NULL,	
	MSG_LABELS 		VARCHAR2(2048) 	NULL,
	ERROR_CODE 		VARCHAR2(64) 	NULL,
	ERROR_REASON 		VARCHAR2(1024) 	NULL,
	ERROR_DETAILS 		VARCHAR2(2048) 	NULL,
  CONSTRAINT PK_WLI_QS_REPORT_ATTRIBUTE PRIMARY KEY(MSG_GUID)
);
CREATE INDEX IX_WLI_QS_REPORT_ATTRIBUTE_DM ON WLI_QS_REPORT_ATTRIBUTE(
	DB_TIMESTAMP, MSG_LABELS );
CREATE INDEX IX_WLI_QS_REPORT_ATTRIBUTE_IED ON WLI_QS_REPORT_ATTRIBUTE(
	INBOUND_SERVICE_NAME, ERROR_CODE, DB_TIMESTAMP);

-- WLI_QS_REPORT_DATA

CREATE TABLE WLI_QS_REPORT_DATA(
	MSG_GUID 		VARCHAR2(64) 	NOT NULL,
        DATA_TYPE	    	SMALLINT        NULL,
        ENCODING		VARCHAR2(24)    NULL,
        DATA_VALUE  		BLOB            NULL,
        CONSTRAINT FK_WLI_QS_REPORT_DATA FOREIGN KEY(MSG_GUID)
	  REFERENCES WLI_QS_REPORT_ATTRIBUTE(MSG_GUID) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IX_WLI_QS_REPORT_DATA ON WLI_QS_REPORT_DATA(MSG_GUID);




