--    Copyright (c) 2005 BEA Systems, Inc.
--    All rights reserved
--
--    THIS IS UNPUBLISHED PROPRIETARY
--    SOURCE CODE OF BEA Systems, Inc.
--    The copyright notice above does not
--    evidence any actual or intended
--    publication of such source code.

-- Replace "$(SCHEMA_USER)" with Schema Owner Name


-- WLI_QS_REPORT_ATTRIBUTE

CREATE TABLE WLI_QS_REPORT_ATTRIBUTE (
	MSG_GUID 		NVARCHAR(64) 	NOT NULL,
	DB_TIMESTAMP 		DATETIME        DEFAULT CURRENT_TIMESTAMP NOT NULL,
	LOCALHOST_TIMESTAMP 	DATETIME 	NOT NULL,
	HOST_NAME 		NVARCHAR(50) 	NOT NULL,
	STATE           NVARCHAR(8)      NOT NULL,
	NODE 		    NVARCHAR(128) 	NULL,
	PIPELINE_NAME 		NVARCHAR(128) 	NULL,
	STAGE_NAME 		NVARCHAR(128) 	NULL,
	INBOUND_SERVICE_NAME 	NVARCHAR(256) 	NOT NULL,
	INBOUND_SERVICE_URI 	NVARCHAR(128) 	NOT NULL,
	INBOUND_OPERATION 	NVARCHAR(64) 	NULL,
	OUTBOUND_SERVICE_NAME 	NVARCHAR(256)	NULL,
	OUTBOUND_SERVICE_URI 	NVARCHAR(256) 	NULL,
	OUTBOUND_OPERATION 	NVARCHAR(64)	NULL,
	MSG_LABELS 		NVARCHAR(2048) 	NULL,
	ERROR_CODE 		NVARCHAR(64) 	NULL,
	ERROR_REASON 		NVARCHAR(1024) 	NULL,
	ERROR_DETAILS 		NVARCHAR(2048) 	NULL,
  CONSTRAINT PK_WLI_QS_REPORT_ATTRIBUTE PRIMARY KEY(MSG_GUID)
)

GO

CREATE VIEW $(SCHEMA_USER).VIEW_WLI_QS_REPORT_ATTRIBUTE_DM WITH SCHEMABINDING
	    AS SELECT MSG_GUID, DB_TIMESTAMP, SUBSTRING(MSG_LABELS, 0, 380) AS M_LABELS
	    FROM $(SCHEMA_USER).WLI_QS_REPORT_ATTRIBUTE
GO

CREATE UNIQUE CLUSTERED INDEX IX_WLI_QS_REPORT_ATTRIBUTE_DM ON $(SCHEMA_USER).VIEW_WLI_QS_REPORT_ATTRIBUTE_DM
    (MSG_GUID, DB_TIMESTAMP, M_LABELS )
GO

CREATE INDEX IX_WLI_QS_REPORT_ATTRIBUTE_IED ON WLI_QS_REPORT_ATTRIBUTE(
	INBOUND_SERVICE_NAME, ERROR_CODE, DB_TIMESTAMP)

GO



-- WLI_QS_REPORT_DATA

CREATE TABLE WLI_QS_REPORT_DATA(
	MSG_GUID 		NVARCHAR(64) 	 NOT NULL,
        DATA_TYPE	    	SMALLINT         NULL,
	ENCODING		NVARCHAR(24)      NULL,
        DATA_VALUE  		IMAGE            NULL,
        CONSTRAINT FK_WLI_QS_REPORT_DATA FOREIGN KEY(MSG_GUID)
	  REFERENCES WLI_QS_REPORT_ATTRIBUTE(MSG_GUID) ON DELETE CASCADE
)
        
GO   

CREATE UNIQUE INDEX IX_WLI_QS_REPORT_DATA ON WLI_QS_REPORT_DATA(MSG_GUID)

GO
