function  WWHBookData_Files(P)
{
P.fA("Introduction to Oracle Service Bus","introOverview.html");
P.fA("Starting Oracle Service Bus Console","introStartingConsole.html");
P.fA("Customizing Table Views","monitoringCustomizeTableViews.html");
P.fA("Change Center","changecenter.html");
P.fA("Using the Change Center","changecenterUsing.html");
P.fA("Activating Sessions","changecenterActivateSession.html");
P.fA("Exiting Sessions","changecenterExiting.html");
P.fA("Viewing Configuration Changes","changecenterViewingChanges.html");
P.fA("Purging Session Activation History","changecenterPurgeTasks.html");
P.fA("Undoing Tasks","changecenterUndoTask.html");
P.fA("Order of Undoing Tasks","changecenterUndoOrder.html");
P.fA("Undoing Into a Session","changecenterUndoIntoSession.html");
P.fA("Viewing Task Details","changecenterViewTaskDetails.html");
P.fA("Viewing All Sessions","changecenterViewAllSessions.html");
P.fA("Viewing and Resolving Conflicts","changecenterViewAndResolveConflicts.html");
P.fA("Working with Projects, Folders, and Resources","projectexplorer.html");
P.fA("Projects View page","projectexplorerListProjects.html");
P.fA("Project/Folder View page","projectexplorerViewandEditProject.html");
P.fA("Adding Projects","projectexplorerAddingProjects.html");
P.fA("Renaming Projects","projectexplorerRenamingProjects.html");
P.fA("Moving Projects (Converting to a Folder)","projectexplorerMoveProject.html");
P.fA("Cloning Projects ","projectexplorerCloneProject.html");
P.fA("Deleting Projects","projectexplorerDeleteProject.html");
P.fA("Adding Folders","projectexplorerAddingFolders.html");
P.fA("Renaming Folders","projectexplorerRenamingFolders.html");
P.fA("Moving or Upgrading Folders","projectexplorerMovingOrUpgradingFolders.html");
P.fA("Cloning Folders","projectexplorerCloningFolders.html");
P.fA("Deleting Folders","projectexplorerDeletingFolders.html");
P.fA("Creating Resources","projectexplorerCreatingResources.html");
P.fA("Loading Resources from a Zip File","projectexplorerLoadingResourcesFromAZipFile.html");
P.fA("Load Resources - Select Zip File and Review Type Extensions page","projectexplorerLoadZippedResources.html");
P.fA("Loading Resources from a URL","projectexplorerLoadingResourcesFromURL.html");
P.fA("Load Resources - Load Resources from URL page","projectexplorerLoadUrlResources.html");
P.fA("Load Resources - Review Loaded Resources page","projectexplorerReviewLoadedResources.html");
P.fA("Load Resources - Import Result page","projectexplorerViewImportResults.html");
P.fA("View References page","projectexplorerViewReferences.html");
P.fA("Viewing References to Resources","projectexplorerViewingReferencesToResources.html");
P.fA("View Change History page","projectexplorerViewChangeHistory.html");
P.fA("Using the Resource Browser","resourcebrowserDisplaying_the_Resource_Browser.html");
P.fA("Renaming Resources","projectexplorerRenameResource.html");
P.fA("Moving Resources","projectexplorerMovingResources.html");
P.fA("Cloning Resources","projectexplorerCloningResources.html");
P.fA("Exporting a WSDL","projectexplorerExportWSDL.html");
P.fA("Generating a WSDL","projectexplorerGenerateWSDL.html");
P.fA("Viewing Resources in a Web Browser","projectexplorerViewingResourcesInAWebBrowser.html");
P.fA("Deleting Resources","projectexplorerDeletingResources.html");
P.fA("XML Schemas","schemas.html");
P.fA("Locating XML Schemas","schemasListandLocateSchemas.html");
P.fA("Adding XML Schemas","schemasAddSchema.html");
P.fA("Editing XML Schemas","schemasViewandChangeSchema.html");
P.fA("Deleting XML Schemas","schemasDeleteSchema.html");
P.fA("Viewing Unresolved XML Schema References","schemasViewUnresolvedSchemaRef.html");
P.fA("Resolving Unresolved XML Schema References","schemasResolveSchema.html");
P.fA("Alert Destinations","alertdestinations.html");
P.fA("Locating Alert Destinations","resourcesViewAllAlertDestinations.html");
P.fA("Adding Alert Destinations","resourceAddAlertDestination.html");
P.fA("Adding E-Mail and JMS Recipients","resourcesAlertDestinationTarget_ActionSpecific.html");
P.fA("Adding E-Mail Recipients","alertdestinationscs.html");
P.fA("Adding JMS Destinations","alertdestinationsct.html");
P.fA("Editing Alert Destinations","resourcesEditAlertDestination.html");
P.fA("Deleting Alert Destinations","alertdestinationsDeleting.html");
P.fA("WSDLs","wsdls.html");
P.fA("Locating WSDLs","wsdlsListandLocateWSDLs.html");
P.fA("Adding WSDLs","wsdlsAddWSDL.html");
P.fA("Editing WSDLs","wsdlsViewandChangeWSDL.html");
P.fA("Deleting WSDLs","wsdlsDeleteWSDL.html");
P.fA("Viewing Unresolved WSDL References","wsdlsViewUnresolvedWSDLRef.html");
P.fA("Resolving Unresolved WSDL References","wsdlsResolveWSDL.html");
P.fA("JARs","jars.html");
P.fA("Locating JARs","resourcesViewingAllJars.html");
P.fA("Adding JARs","resourcesAddingJAR.html");
P.fA("Editing JARs","resourcesEditingJAR.html");
P.fA("Editing JAR Dependencies","resourcesEditArchiveDependencies.html");
P.fA("Deleting JARs","resourcesDeleteJAR.html");
P.fA("MQ Connections","mq_connection.html");
P.fA("Locating MQ Connections","resourcesViewingAllMQConnectionCustomResources.html");
P.fA("Adding MQ Connections","resourcesAddingMQConnectionCustomResource.html");
P.fA("Editing MQ Connections","resourcesEditingMQConnectionCustomResource.html");
P.fA("Deleting MQ Connections","resourcesDeletingMQConnectionCustomResource.html");
P.fA("Split-Joins","split_join.html");
P.fA("Locating Split-Joins","resourcesViewAllSplitJoins.html");
P.fA("Adding Split-Joins","resourcesAddSplitJoins.html");
P.fA("Editing Split-Joins","resourcesEditSplitJoins.html");
P.fA("Deleting Split-Joins","resourcesDeleteSplitJoins.html");
P.fA("XQuery Transformations","xquerytransforms.html");
P.fA("Locating XQuery Transformations","xquerytransformationListandLocateXQueryTransforms.html");
P.fA("Adding XQuery Transformations","xquerytransformationAddXQueryTransform.html");
P.fA("Editing XQuery Transformations","xquerytransformationViewandChangeTransformation.html");
P.fA("Deleting an XQuery Transformation","xquerytransformationDelete.html");
P.fA("Custom WS-Policies","policies.html");
P.fA("Locating Custom WS-Policies","policiesListandLocatePolicies.html");
P.fA("Adding Custom WS-Policies","policiesAddPolicy.html");
P.fA("Editing Custom WS-Policies","policiesViewandChangePolicies.html");
P.fA("Deleting Custom WS-Policies","policiesDeletePolicy.html");
P.fA("JCA Bindings","jca.html");
P.fA("Locating JCA Bindings","jcasListandLocateJCA.html");
P.fA("Adding JCA Bindings","jcasAddJCA.html");
P.fA("Editing JCA Bindings","jcasViewandChangeJCA.html");
P.fA("Deleting JCA Bindings","jcaep.html");
P.fA("XML Documents","xml.html");
P.fA("Locating XML Documents","xmlListandLocateXML.html");
P.fA("Adding XML Documents","xmlAddXML.html");
P.fA("Editing XML Documents","xmlViewandChangeXML.html");
P.fA("Deleting XML Documents","xmlDeleteXML.html");
P.fA("XSL Transformations","xslttransforms.html");
P.fA("Locating XSL Transformations","xslttransformationListandLocateXSLTTransforms.html");
P.fA("Adding an XSL Transformation","xslttransformationAddXSLTTransform.html");
P.fA("Editing XSL Transformations","xslttransformationViewandChangeXSLTTransform.html");
P.fA("Deleting an XSL Transformation","xslttransformationDeleteXSLTTransform.html");
P.fA("Resolving Unresolved XSL Transformation References","xslttransformationResolvingUnresolvedXSLTs.html");
P.fA("MFLs","mfls.html");
P.fA("Locating MFLs","MFLsListandLocateMFLs.html");
P.fA("Adding MFLs","MFLsAddMFL.html");
P.fA("Editing MFLs","MFLsViewandChangeMFL.html");
P.fA("Deleting MFLs","MFLsDeleteMFL.html");
P.fA("Service Accounts","serviceAccounts.html");
P.fA("Specifying Service Accounts","serviceAccountsfh.html");
P.fA("Using Service Accounts Data and Sessions","serviceAccountsfi.html");
P.fA("Locating Service Accounts","serviceAccountsListandLocateServiceAccounts.html");
P.fA("Adding Service Accounts","serviceAccountsAddServiceAccount.html");
P.fA("Editing Service Accounts","serviceAccountsViewandChangeServiceAccount.html");
P.fA("Deleting Service Accounts","serviceAccountsDeleteServiceAccount.html");
P.fA("Service Key Providers","proxyServiceProviders.html");
P.fA("Locating Service Key Providers","proxyServiceProvidersListandLocateProxyServiceProviders.html");
P.fA("Adding Service Key Providers","proxyServiceProvidersAddProxyServiceProvider.html");
P.fA("Editing Service Key Providers","proxyServiceProvidersViewandChangeProxyServiceProvider.html");
P.fA("Deleting Service Key Providers","proxyServiceProvidersDeleteProxyServiceProvider.html");
P.fA("Business Services: Creating and Managing","businessServices.html");
P.fA("Creating and Configuring Business Services","businessServiceAddBusinessService.html");
P.fA("Create/Edit a Business Service - Page Reference","bizSvcCreateBusinessServicePage.html");
P.fA("General Configuration page","bizSvcGeneralConfigurationPage.html");
P.fA("Message Type Configuration page","bizSvcMessageTypeConfigurationPage.html");
P.fA("Transport Configuration page","bizSvcTransportConfigurationPage.html");
P.fA("Protocol-Specific Transport Configuration page","bizSvcProtocolSpecificTransportConfigurationPage.html");
P.fA("BPEL-10g Transport Configuration Page","bizSvcBPEL10GTransportConfigurationPage.html");
P.fA("DSP Transport Configuration page","bizSvcDSPTransportConfigurationPage.html");
P.fA("EJB Transport Configuration page","bizSvcEJBTransportConfigurationPage.html");
P.fA("E-Mail Transport Configuration page","bizSvcEMailTransportConfigurationPage.html");
P.fA("File Transport Configuration page","bizSvcFileTransportConfigurationPage.html");
P.fA("Flow Transport Configuration page","bizSvcFlowTransportConfigurationPage.html");
P.fA("FTP Transport Configuration page","bizSvcFTPTransportConfigurationPage.html");
P.fA("HTTP Transport Configuration Page","bizSvcHTTPTransportConfigurationPage.html");
P.fA("JCA Transport Configuration Page","bizSvcJCATransportConfigurationPage.html");
P.fA("JEJB Transport Configuration Page","bizSvcJEJBTransportConfigurationPage.html");
P.fA("JMS Transport Configuration page","bizSvcJMSTransportConfigurationPage.html");
P.fA("MQ Transport Configuration page","bizSvcMQTransportConfigurationPage.html");
P.fA("SB Transport Configuration page","bizSvcSBTransportConfigurationPage.html");
P.fA("SFTP Transport Configuration page","bizSvcSFTPTransportConfigurationPage.html");
P.fA("SOA-DIRECT Transport Configuration page","bizSvcSOADIRECTTransportConfigurationPage.html");
P.fA("Tuxedo Transport Configuration page","bizSvcTuxedoTransportConfigurationPage.html");
P.fA("WS Transport Configuration page","bizSvcWSTransportConfigurationPage.html");
P.fA("SOAP Binding Configuration page","bizSvcSOAPConfigurationPage.html");
P.fA("Message Handling Configuration Page","bizSvcMessageContentHandlingConfigurationPage.html");
P.fA("Summary page","bizSvcSummaryPage.html");
P.fA("Exporting a WSDL Associated with a Business Service","businessserviceExportBusinessServiceAsWSDL.html");
P.fA("Locating Business Services","businessServiceListandLocateBusinessServices.html");
P.fA("Editing Business Service Configurations","BusinessServiceViewandChangeBusinessServices.html");
P.fA("View a Business Service - Configuration Details page","businessserviceViewBusinessServiceConfigurationDetailsPage.html");
P.fA("Business Service Policies page","businessserviceViewBusinessServicePolicyConfigurationPage.html");
P.fA("Business Service Security page","businessserviceViewBusinessServiceSecurityConfigurationPage.html");
P.fA("Deleting Business Services","businessserviceDeleteBusinessService.html");
P.fA("Proxy Services: Creating and Managing","proxyservices.html");
P.fA("Creating and Configuring Proxy Services","proxyserviceCreateAndConfigureProxyServices.html");
P.fA("Create/Edit a Proxy Service - Page Reference","proxyserviceCreateProxyServicePage.html");
P.fA("General Configuration page","proxyserviceCreateProxyServiceGeneralConfigurationPage.html");
P.fA("Message Type Configuration page","proxyserviceCreateProxyServiceMessageTypeConfigurationPage.html");
P.fA("Transport Configuration page","proxyserviceCreateProxyServiceTransportConfigurationPage.html");
P.fA("Protocol-Specific Transport Configuration Pages","proxyserviceCreateProxyServiceTransportSpecificConfigurationPage.html");
P.fA("E-Mail Transport Configuration page","proxyserviceCreateProxyServiceEMailTransportConfigurationPage.html");
P.fA("File Transport Configuration page","proxyserviceCreateProxyServiceFileTransportConfigurationPage.html");
P.fA("FTP Transport Configuration page","proxyserviceCreateProxyServiceFTPTransportConfigurationPage.html");
P.fA("HTTP Transport Configuration Page","proxyserviceCreateProxyServiceHTTPTransportConfigurationPage.html");
P.fA("JCA Transport Configuration Page","proxyserviceCreateProxyServiceJCATransportConfigurationPage.html");
P.fA("JEJB Transport Configuration page","proxyserviceCreateProxyServiceJEJBTransportConfigurationPage.html");
P.fA("JMS Transport Configuration page","proxyserviceCreateProxyServiceJMSTransportConfigurationPage.html");
P.fA("MQ Transport Configuration page","proxyserviceCreateProxyServiceMQTransportConfigurationPage.html");
P.fA("SB Transport Configuration page","proxyserviceCreateProxyServiceSBTransportConfigurationPage.html");
P.fA("SFTP Transport Configuration page","proxyserviceCreateProxyServiceSFTPTransportConfigurationPage.html");
P.fA("Tuxedo Transport Configuration page","proxyserviceCreateProxyServiceTuxedoTransportConfigurationPage.html");
P.fA("WS Transport Configuration page","proxyserviceCreateProxyServiceWSTransportConfigurationPage.html");
P.fA("Operation Selection Configuration page","proxyserviceCreateProxyServiceOperationSelectionConfigurationPage.html");
P.fA("Message Handling page","proxyserviceCreateProxyServiceMessageContentHandlingPage.html");
P.fA("Summary page","proxyserviceCreateProxyServiceSummaryPage.html");
P.fA("Exporting a WSDL Associated with a Proxy Service","proxyserviceExportProxyServiceAsWSDL.html");
P.fA("Locating Proxy Services","proxyserviceListandLocateProxyServices.html");
P.fA("Editing Proxy Service Configurations","proxyserviceViewandModifyProxyServices.html");
P.fA("View a Proxy Service - Configuration Details page","proxyserviceViewProxyServiceConfigurationDetailsPage.html");
P.fA("Proxy Service Policy page","proxyserviceViewProxyServicePolicyConfigurationPage.html");
P.fA("Proxy Service Security page","proxyserviceViewProxyServiceSecurityConfigurationPage.html");
P.fA("Deleting Proxy Services","proxyserviceDeleteProxyService.html");
P.fA("Proxy Services: Message Flow","proxymessageflow.html");
P.fA("Creating, Editing, and Viewing Message Flows","proxyserviceCreateEditViewMessageFlows.html");
P.fA("Edit Message Flow page","proxyserviceEditMessageFlowPage.html");
P.fA("Edit Stage Configuration Page","proxyserviceEditStageConfigurationPage.html");
P.fA("Adding Pipeline Pair Nodes to Message Flows","proxyserviceAddPipelinePair.html");
P.fA("Adding Conditional Branches to Message Flows","proxyserviceAddConditionalBranchNode.html");
P.fA("Adding Operational Branches to Message Flows","proxyserviceAddOperationalBranchNode.html");
P.fA("Adding Stages to Pipelines","proxyserviceAddStage.html");
P.fA("Adding Route Nodes to Message Flows","proxyserviceAddRouteNode.html");
P.fA("Cutting, Copying, and Pasting Stages and Route Nodes","proxyserviceCutCopyPasteStagesAndRouteNodes.html");
P.fA("Proxy Services: Actions","proxyactions.html");
P.fA("Adding and Editing Actions in Message Flows","proxyactionsAddAction.html");
P.fA("Adding Publish Actions","proxyactionsPublishAction.html");
P.fA("Adding Publish Table Actions","proxyactionsPublishTableAction.html");
P.fA("Adding Dynamic Publish Actions","proxyactionsDynamicPublish.html");
P.fA("Adding Routing Options Actions","proxyactionsRoutingOptions.html");
P.fA("Adding Service Callout Actions","proxyactionsServiceCalloutAction.html");
P.fA("Adding Transport Header Actions","proxyactionsTransportHeadersAction.html");
P.fA("Adding Dynamic Routing to Route Nodes","proxyactionsAddingDynamicRoutingToRouteNodes.html");
P.fA("Adding Routing Actions to Route Nodes","proxyactionsRoutingActions.html");
P.fA("Adding Routing Tables to Route Nodes","proxyactionslo.html");
P.fA("Adding For Each Actions","proxyactionsForEachAction.html");
P.fA("Adding If... Then... Actions","proxyactionsIfThenAction.html");
P.fA("Adding Raise Error Actions","proxyactionsRaiseErrorAction.html");
P.fA("Adding Reply Actions","proxyactionsReplyAction.html");
P.fA("Adding Resume Actions","proxyactionsResumeAction.html");
P.fA("Adding Skip Actions","proxyactionsSkipAction.html");
P.fA("Adding Assign Actions","proxyactionsAssignAction.html");
P.fA("Adding Delete Actions","proxyactionsDeleteAction.html");
P.fA("Adding Insert Actions","proxyactionsInsertAction.html");
P.fA("Adding Java Callout Actions","proxyactionsJavaCallout.html");
P.fA("Adding MFL Transform Actions","proxyactionsMFLTransformAction.html");
P.fA("Adding Rename Actions","proxyactionsRenameAction.html");
P.fA("Adding Replace Actions","proxyactionsReplaceAction.html");
P.fA("Adding Validate Actions","proxyactionsValidateAction.html");
P.fA("Adding Alert Actions","proxyactionsAlertAction.html");
P.fA("Adding Log Actions","proxyactionsLogAction.html");
P.fA("Adding Report Actions","proxyactionsReportAction.html");
P.fA("Proxy Services: XQuery and XPath Editors","proxyeditors.html");
P.fA("Creating and Editing Inline XQuery and XPath Expressions","proxyservicesCreatingAndEditingInlineExpressions.html");
P.fA("Understanding XQuery Editor Layouts and Tasks","proxyserviceXQueryEditorLayouts.html");
P.fA("Building Expressions in the Editor Workspace Text Fields","proxyserviceBuildingExpressionsInTextFields.html");
P.fA("Creating Namespaces to Use in Inline Expressions ","proxyserviceCreatingNamespaces.html");
P.fA("Creating Variable Structures in the XQuery Editors","proxyserviceDefineVariableStructure.html");
P.fA("Creating Custom XPath Functions in the XQuery Editors","proxyserviceDefineXpathFunctions.html");
P.fA("Binding External XQuery Resources to Inline XQueries","proxyserviceSelectXQueryResource.html");
P.fA("Binding External XSLT Resources to Inline XQueries","proxyserviceSelectXSLTResource.html");
P.fA("Binding Dynamic XQuery Expressions to Inline XQueries","proxyserviceDynamicXQuery.html");
P.fA("Entering XQuery Comparison Expressions Using the Builder Option","proxyserviceEnterComparisonExpression.html");
P.fA("Entering Unary Expressions Using the Builder Option","proxyserviceEnterUnaryExpression.html");
P.fA("Proxy Services: Error Handlers","proxyerrors.html");
P.fA("Edit Error Handler page","proxyserviceEditErrorHandlerPage.html");
P.fA("Adding Proxy Service Error Handlers","proxyserviceAddErrorHandlerProxyService.html");
P.fA("Adding Pipeline Error Handlers","proxyserviceAddErrorHandlerPipeline.html");
P.fA("Adding Stage Error Handlers","proxyserviceAddErrorHandlerStage.html");
P.fA("Adding Route Node Error Handlers","proxyserviceAddErrorHandlerRouteNode.html");
P.fA("Editing Error Handlers","proxyserviceViewandChangeErrorHandler.html");
P.fA("Security Configuration","securityconfiguration.html");
P.fA("Understanding Users, Groups, Security Roles and Policies","securityconfigurationop.html");
P.fA("Locating Users","securityconfigurationListandLocateUsers.html");
P.fA("Adding Users","securityconfigurationAddUser.html");
P.fA("Editing Users","securityconfigurationViewandChangeUserDetails.html");
P.fA("Deleting Users","securityconfigurationDeleteUser.html");
P.fA("Locating Groups","securityconfigurationListandLocateGroups.html");
P.fA("Adding Groups","securityconfigurationAddGroup.html");
P.fA("Editing Groups","securityconfigurationAddGroupa.html");
P.fA("Deleting Groups","securityconfigurationDeleteGroup.html");
P.fA("Locating Roles","securityconfigurationListandLocateRoles.html");
P.fA("Adding Roles","securityconfigurationAddRole.html");
P.fA("Defining Role Conditions","securityconfigurationpb.html");
P.fA("Editing Roles","securityconfigurationViewandChangeRoleDetails.html");
P.fA("Deleting Roles","securityconfigurationDeleteRole.html");
P.fA("Locating Access Control Policies","securityconfigurationListandLocateAccessControls.html");
P.fA("Editing Transport-Level Access Policies","securityconfigurationEditTransportAuthorizationPolicies.html");
P.fA("Editing Message-Level Access Policies","securityconfigurationEditServiceAuthorizationPolicies.html");
P.fA("Adding Policy Conditions","securityconfigurationAddingPolicyConditions.html");
P.fA("Monitoring","monitoring.html");
P.fA("Viewing SLA Alerts","monitoringViewDashboardSLAStatistics.html");
P.fA("Viewing Pipeline Alerts","monitoringViewDashboardPipelineStatistics.html");
P.fA("Locating Alerts","monitoringLocateAlerts.html");
P.fA("Purging Alerts","monitoringPurgeAlerts.html");
P.fA("Viewing Alert Details","monitoringViewAlertDetails.html");
P.fA("Viewing Service Monitoring Information","monitoringListandLocateServices.html");
P.fA("Resetting Statistics for Services","monitoringResetStatistics.html");
P.fA("Configuring Operational Settings for Proxy Services","proxyserviceEditOperatonalSettingsPage.html");
P.fA("Configuring Operational Settings for Business Services","bizserviceEditOperatonalSettingsPage.html");
P.fA("Setting the Aggregation Interval for a Service","monitoringSetAggregationInterval.html");
P.fA("Viewing Service Metrics","monitoringViewServiceMetrics.html");
P.fA("Viewing Operations Metrics for WSDL-Based Services","monitoringViewOperationsMetrics.html");
P.fA("Viewing Pipeline Metrics","monitoringViewPipelineMetrics.html");
P.fA("Viewing Action Metrics","monitoringViewActionMetrics.html");
P.fA("Viewing Business Services Endpoint URIs Metrics","monitoringViewEndpointsMetrics.html");
P.fA("Viewing Server Information","monitoringListandLocateServers.html");
P.fA("Viewing Server Details","monitoringViewServerDetails.html");
P.fA("Viewing Domain Log Files","monitoringViewServerLogFiles.html");
P.fA("Customizing Your View of Domain Log File Entries","monitoringCustomizeDomainLogFileEntries.html");
P.fA("Viewing Details of Domain Log Files","monitoringServerLogDetails.html");
P.fA("Viewing Alert Rules","monitoringListandLocateAlertRules.html");
P.fA("Locating Alert Rules","monitoringLocateAlertRules.html");
P.fA("Creating and Editing Alert Rules","monitoringCreateAlertRule.html");
P.fA("Configuring General Information for Alert Rules","monitoringEditAlertRuleDetails.html");
P.fA("Defining Alert Rule Conditions","monitoringDefineAlertRule.html");
P.fA("Reviewing the Alert Rule Configuration","monitoringReviewAlertRuleDetails.html");
P.fA("Viewing Alert Rule Configurations","monitoringViewAlertRuleDetails.html");
P.fA("Editing Alert Rules","monitoringEditAlertRuleDetailsb.html");
P.fA("Deleting Alert Rules","monitoringDeleteAlertRule.html");
P.fA("Configuration","configuration.html");
P.fA("Finding and Updating Operational Settings","configurationListandLocateSystemResources.html");
P.fA("Finding All Services (Proxy and Business Services)","configurationFindAllServices.html");
P.fA("Finding Proxy Services","configurationFindProxyServices.html");
P.fA("Finding Business Services","configurationFindBusinessServices.html");
P.fA("Finding Split-Joins","configurationFindSplitJoins.html");
P.fA("Finding Alert Destinations","configurationFindAlertDestinations.html");
P.fA("Finding SLA Alert Rules","configurationFindSLAAlertRules.html");
P.fA("Enabling Global Settings","configurationEnablingGlobalSettings.html");
P.fA("Enabling Global Monitoring of Services","configurationEnablingGlobalMonitoring.html");
P.fA("Disabling Global Monitoring of Services","configurationDisablingGlobalMonitoring.html");
P.fA("Enabling SLA Alerts Globally","configurationEnablingSLAAlertsGlobally.html");
P.fA("Disabling SLA Alerts Globally","configurationDisablingSLAAlertsGlobally.html");
P.fA("Enabling Pipeline Alerts Globally","configurationEnablingPipelineAlertsGlobally.html");
P.fA("Disabling Pipeline Alerts Globally","configurationDisablingPipelineAlertsGlobally.html");
P.fA("Enabling Message Reporting Globally","configurationEnablingMessageReportingGlobally.html");
P.fA("Disabling Message Reporting Globally","configurationDisablingMessageReportingGlobally.html");
P.fA("Enabling Logging Globally","configurationEnablingLoggingGlobally.html");
P.fA("Disabling Logging Globally","configurationDisablingLoggingGlobally.html");
P.fA("Enabling Result Caching Globally","configurationEnablingCachingGlobally.html");
P.fA("Disabling Result Caching Globally","configurationDisablingCachingGlobally.html");
P.fA("Setting User Preferences","configurationSettingUserPreferences.html");
P.fA("Reporting","reporting.html");
P.fA("Viewing Reporting Messages","reportingListandLocateMessages.html");
P.fA("Viewing Message Details","reportingViewMessageDetails.html");
P.fA("Purging Messages","reportingPurgeMessages.html");
P.fA("Import/Export","import_export.html");
P.fA("Importing Resources","systemadminImportConfigurationData.html");
P.fA("Selecting Projects and Resources to Import","systemadminSelectingResources.html");
P.fA("Specifying the Importing Security Settings","systemadminImportSecuritySettings.html");
P.fA("Importing Service Accounts or Service Key Providers","systemadminImportServiceAccounts.html");
P.fA("Reviewing the Import Summary","systemadminImportSummary.html");
P.fA("Exporting Resources","systemadminExportConfigurationData.html");
P.fA("Specifying the Exporting Security Settings","systemadminExportSecuritySettings.html");
P.fA("UDDI","uddi.html");
P.fA("Viewing Configured UDDI Registries","systemadminRegistryConfiguration.html");
P.fA("Configuring UDDI Registries","systemadminConfigChangesRegistry.html");
P.fA("Adding UDDI Registries","uddiuo.html");
P.fA("Editing UDDI Registries","uddiup.html");
P.fA("Setting Up a Default UDDI Configuration","systemadminDefaultRegistry.html");
P.fA("Importing Business Services From a UDDI Registry","systemadminImportFromRegistry.html");
P.fA("Using Auto-Import Status","systemadminAutoImport.html");
P.fA("Detaching Services","systemadminDetachService.html");
P.fA("Publishing Proxy Services to a UDDI Registry","systemadminPublishToRegistry.html");
P.fA("Using Auto-Publish","systemadminAutoPublish.html");
P.fA("Global Resources","global_resources.html");
P.fA("Viewing JNDI Providers","systemadminViewAllJNDI.html");
P.fA("Adding JNDI Providers","systemadminAddJNDI.html");
P.fA("Editing JNDI Providers","systemadminEditJNDI.html");
P.fA("Deleting JNDI Providers ","systemadminDeleteJNDIProvider.html");
P.fA("Viewing SMTP Servers","systemadminViewAllSMTP.html");
P.fA("Locating SMTP Servers","systemadminListLocateSMTP.html");
P.fA("Adding SMTP Servers","systemadminSMTPAdding.html");
P.fA("Configuring a Default SMTP Server","systemadminSMTPDefaultConfig.html");
P.fA("Editing SMTP Servers","systemadminEditSMTP.html");
P.fA("Deleting SMTP Servers ","systemadminSMTPDeleting.html");
P.fA("Viewing Proxy Servers","systemadminViewAllProxy.html");
P.fA("Locating Proxy Servers","systemadminListLocateProxy.html");
P.fA("Adding Proxy Servers","systemadminProxyAdding.html");
P.fA("Editing Proxy Servers","systemadminEditProxy.html");
P.fA("Deleting Proxy Servers ","systemadminProxyDeleting.html");
P.fA("Customization","customization.html");
P.fA("Finding and Replacing Environment Values","systemadminFindandReplace.html");
P.fA("Creating Customization Files","systemadminCreateCustomizationFiles.html");
P.fA("Executing Customization Files","systemadminExecuteCustomizationFiles.html");
P.fA("Test Console","testing.html");
P.fA("Testing Services","testingServices.html");
P.fA("Testing Proxy Services","testingwu.html");
P.fA("Configuring Proxy Services Test Data","testingwv.html");
P.fA("Viewing Proxy Services Test Results","testingww.html");
P.fA("Tracing Proxy Services","testingwz.html");
P.fA("Testing Business Services","testingwy.html");
P.fA("Configuring Business Services Test Data","testingza.html");
P.fA("Viewing Business Services Test Results","testingzb.html");
P.fA("Testing Transformations","testingResources.html");
P.fA("Testing MFL Transformations","testingzc.html");
P.fA("Testing XSLT Transformations","testingzd.html");
P.fA("Testing XQuery Transformations","testingze.html");
P.fA("Performing XQuery Testing","testingInlineXQuery.html");
P.fA("Using the XQuery Expression and XQuery Condition Editors","testingzf.html");
P.fA("Using the XPath Expression Editor","testingzg.html");
P.fA("Understanding How the Run Time Uses the Transport Settings in the Test Console","testConsoleTransports.html");
P.fA("Error Codes","errorcodes.html");
}
