DROP TABLE RM_DESTINATION_MESSAGE_INFO CASCADE CONSTRAINTS;

DROP TABLE RM_DESTINATION_GROUP_INFO CASCADE CONSTRAINTS;

DROP TABLE RM_SOURCE_MESSAGE_INFO CASCADE CONSTRAINTS;

DROP TABLE RM_SOURCE_GROUP_INFO CASCADE CONSTRAINTS;

COMMIT;