Rem
Rem $Header: jazn/jps/schema/oracle/opss_upgrade_11114_11117.sql /st_entsec_11.1.1.7.0/1 2012/10/24 22:33:57 jianz Exp $
Rem
Rem opss_upgrade_11114_11117.sql
Rem
Rem Copyright (c) 2011, 2012, Oracle and/or its affiliates. 
Rem All rights reserved. 
Rem
Rem    NAME
Rem      opss_upgrade_11114_11117.sql - <one-line expansion of the name>
Rem
Rem    DESCRIPTION
Rem      <short description of component this file declares/defines>
Rem
Rem    NOTES
Rem      <other useful comments, qualifications, etc.>
Rem
Rem    MODIFIED   (MM/DD/YY)
Rem    jianz       09/02/12 - Created, PS6 upgrade from PS3/PS4
Rem

ALTER SESSION SET CURRENT_SCHEMA=&&1;

-- update indexes
DROP INDEX IDX_JPS_PARENTDN;
CREATE INDEX IDX_JPS_ID_PARENTDN ON JPS_DN (ENTRYID, PARENTDN);
DROP INDEX IDX_CT_0_ATTRVAL;
DROP INDEX IDX_CT_1_ATTRVAL;
DROP INDEX IDX_CT_2_ATTRVAL;
DROP INDEX IDX_CT_3_ATTRVAL;
DROP INDEX IDX_CT_4_ATTRVAL;
DROP INDEX IDX_CT_5_ATTRVAL;
DROP INDEX IDX_CT_6_ATTRVAL;
DROP INDEX IDX_CT_7_ATTRVAL;
DROP INDEX IDX_CT_8_ATTRVAL;
DROP INDEX IDX_CT_9_ATTRVAL;
DROP INDEX IDX_CT_10_ATTRVAL;
DROP INDEX IDX_CT_11_ATTRVAL;
DROP INDEX IDX_CT_12_ATTRVAL;
DROP INDEX IDX_CT_13_ATTRVAL;
DROP INDEX IDX_CT_14_ATTRVAL;
DROP INDEX IDX_CT_15_ATTRVAL;
DROP INDEX IDX_CT_16_ATTRVAL;
DROP INDEX IDX_CT_17_ATTRVAL;
DROP INDEX IDX_CT_18_ATTRVAL;
DROP INDEX IDX_CT_19_ATTRVAL;
DROP INDEX IDX_CT_20_ATTRVAL;
DROP INDEX IDX_CT_21_ATTRVAL;
DROP INDEX IDX_CT_22_ATTRVAL;
DROP INDEX IDX_CT_23_ATTRVAL;
DROP INDEX IDX_CT_24_ATTRVAL;
DROP INDEX IDX_CT_25_ATTRVAL;
DROP INDEX IDX_CT_26_ATTRVAL;
DROP INDEX IDX_CT_27_ATTRVAL;
DROP INDEX IDX_CT_28_ATTRVAL;
DROP INDEX IDX_CT_29_ATTRVAL;
DROP INDEX IDX_CT_30_ATTRVAL;
DROP INDEX IDX_CT_31_ATTRVAL;
DROP INDEX IDX_CT_32_ATTRVAL;
DROP INDEX IDX_CT_33_ATTRVAL;
CREATE INDEX IDX_CT_0_ATTRVAL ON CT_0 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_1_ATTRVAL ON CT_1 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_2_ATTRVAL ON CT_2 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_3_ATTRVAL ON CT_3 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_4_ATTRVAL ON CT_4 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_5_ATTRVAL ON CT_5 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_6_ATTRVAL ON CT_6 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_7_ATTRVAL ON CT_7 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_8_ATTRVAL ON CT_8 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_9_ATTRVAL ON CT_9 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_10_ATTRVAL ON CT_10 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_11_ATTRVAL ON CT_11 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_12_ATTRVAL ON CT_12 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_13_ATTRVAL ON CT_13 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_14_ATTRVAL ON CT_14 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_15_ATTRVAL ON CT_15 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_16_ATTRVAL ON CT_16 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_17_ATTRVAL ON CT_17 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_18_ATTRVAL ON CT_18 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_19_ATTRVAL ON CT_19 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_20_ATTRVAL ON CT_20 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_21_ATTRVAL ON CT_21 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_22_ATTRVAL ON CT_22 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_23_ATTRVAL ON CT_23 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_24_ATTRVAL ON CT_24 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_25_ATTRVAL ON CT_25 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_26_ATTRVAL ON CT_26 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_27_ATTRVAL ON CT_27 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_28_ATTRVAL ON CT_28 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_29_ATTRVAL ON CT_29 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_30_ATTRVAL ON CT_30 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_31_ATTRVAL ON CT_31 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_32_ATTRVAL ON CT_32 (ATTRVAL, JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_33_ATTRVAL ON CT_33 (ATTRVAL, JPS_DN_ENTRYID);

---opss_tables upgrade

ALTER TABLE JPS_CHANGELOG
ADD ENTITYTYPE    VARCHAR2(1024);
ALTER TABLE JPS_CHANGELOG
ADD ENTITYNAME    VARCHAR2(1024);
ALTER TABLE JPS_CHANGELOG
ADD POLICYDOMAINNAME VARCHAR2(1024);
ALTER TABLE JPS_CHANGELOG
ADD TID           VARCHAR2(1024);
ALTER TABLE JPS_CHANGELOG
ADD CHANGELOGTYPE VARCHAR2(1024);


CREATE TABLE CT_34 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_34_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_34_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_34_DNID ON CT_34 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_34_ATTRVAL ON CT_34 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_35 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_35_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_35_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_35_DNID ON CT_35 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_35_ATTRVAL ON CT_35 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_36 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_36_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_36_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_36_DNID ON CT_36 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_36_ATTRVAL ON CT_36 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_37 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_37_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_37_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_37_DNID ON CT_37 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_37_ATTRVAL ON CT_37 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_38 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_38_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_38_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_38_DNID ON CT_38 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_38_ATTRVAL ON CT_38 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_39 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_39_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_39_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_39_DNID ON CT_39 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_39_ATTRVAL ON CT_39 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_40 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_40_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_40_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_40_DNID ON CT_40 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_40_ATTRVAL ON CT_40 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_41 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_41_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_41_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_41_DNID ON CT_41 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_41_ATTRVAL ON CT_41 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_42 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_42_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_42_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_42_DNID ON CT_42 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_42_ATTRVAL ON CT_42 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_43 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_43_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_43_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_43_DNID ON CT_43 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_43_ATTRVAL ON CT_43 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_44 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_44_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_44_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_44_DNID ON CT_44 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_44_ATTRVAL ON CT_44 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_45 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_45_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_45_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_45_DNID ON CT_45 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_45_ATTRVAL ON CT_45 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_46 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_46_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_46_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_46_DNID ON CT_46 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_46_ATTRVAL ON CT_46 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_47 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_47_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_47_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_47_DNID ON CT_47 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_47_ATTRVAL ON CT_47 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_48 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_48_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_48_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_48_DNID ON CT_48 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_48_ATTRVAL ON CT_48 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_49 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_49_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_49_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_49_DNID ON CT_49 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_49_ATTRVAL ON CT_49 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_50 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_50_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_50_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_50_DNID ON CT_50 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_50_ATTRVAL ON CT_50 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_51 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_51_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_51_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_51_DNID ON CT_51 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_51_ATTRVAL ON CT_51 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_52 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_52_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_52_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_52_DNID ON CT_52 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_52_ATTRVAL ON CT_52 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_53 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_53_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_53_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_53_DNID ON CT_53 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_53_ATTRVAL ON CT_53 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_54 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_54_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_54_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_54_DNID ON CT_54 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_54_ATTRVAL ON CT_54 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_55 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_55_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_55_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_55_DNID ON CT_55 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_55_ATTRVAL ON CT_55 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_56 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_56_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_56_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_56_DNID ON CT_56 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_56_ATTRVAL ON CT_56 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_57 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_57_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_57_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_57_DNID ON CT_57 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_57_ATTRVAL ON CT_57 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_58 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_58_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_58_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_58_DNID ON CT_58 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_58_ATTRVAL ON CT_58 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_59 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_59_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_59_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_59_DNID ON CT_59 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_59_ATTRVAL ON CT_59 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_60 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_60_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_60_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_60_DNID ON CT_60 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_60_ATTRVAL ON CT_60 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_61 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_61_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_61_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_61_DNID ON CT_61 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_61_ATTRVAL ON CT_61 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_62 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_62_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_62_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_62_DNID ON CT_62 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_62_ATTRVAL ON CT_62 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_63 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_63_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_63_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_63_DNID ON CT_63 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_63_ATTRVAL ON CT_63 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_64 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_64_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_64_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_64_DNID ON CT_64 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_64_ATTRVAL ON CT_64 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_65 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_65_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_65_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_65_DNID ON CT_65 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_65_ATTRVAL ON CT_65 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_66 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_66_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_66_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_66_DNID ON CT_66 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_66_ATTRVAL ON CT_66 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_67 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_67_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_67_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_67_DNID ON CT_67 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_67_ATTRVAL ON CT_67 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_68 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_68_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_68_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_68_DNID ON CT_68 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_68_ATTRVAL ON CT_68 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_69 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_69_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_69_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_69_DNID ON CT_69 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_69_ATTRVAL ON CT_69 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_70 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_70_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_70_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_70_DNID ON CT_70 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_70_ATTRVAL ON CT_70 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_71 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_71_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_71_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_71_DNID ON CT_71 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_71_ATTRVAL ON CT_71 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_72 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_72_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_72_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_72_DNID ON CT_72 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_72_ATTRVAL ON CT_72 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_73 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_73_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_73_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_73_DNID ON CT_73 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_73_ATTRVAL ON CT_73 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_74 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_74_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_74_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_74_DNID ON CT_74 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_74_ATTRVAL ON CT_74 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_75 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_75_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_75_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_75_DNID ON CT_75 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_75_ATTRVAL ON CT_75 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_76 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_76_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_76_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_76_DNID ON CT_76 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_76_ATTRVAL ON CT_76 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_77 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_77_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_77_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_77_DNID ON CT_77 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_77_ATTRVAL ON CT_77 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_78 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_78_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_78_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_78_DNID ON CT_78 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_78_ATTRVAL ON CT_78 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_79 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_79_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_79_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_79_DNID ON CT_79 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_79_ATTRVAL ON CT_79 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_80 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_80_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_80_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_80_DNID ON CT_80 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_80_ATTRVAL ON CT_80 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_81 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_81_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_81_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_81_DNID ON CT_81 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_81_ATTRVAL ON CT_81 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_82 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_82_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_82_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_82_DNID ON CT_82 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_82_ATTRVAL ON CT_82 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_83 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_83_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_83_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_83_DNID ON CT_83 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_83_ATTRVAL ON CT_83 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_84 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_84_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_84_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_84_DNID ON CT_84 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_84_ATTRVAL ON CT_84 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_85 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_85_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_85_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_85_DNID ON CT_85 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_85_ATTRVAL ON CT_85 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_86 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_86_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_86_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_86_DNID ON CT_86 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_86_ATTRVAL ON CT_86 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_87 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_87_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_87_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_87_DNID ON CT_87 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_87_ATTRVAL ON CT_87 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_88 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_88_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_88_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_88_DNID ON CT_88 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_88_ATTRVAL ON CT_88 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_89 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_89_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_89_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_89_DNID ON CT_89 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_89_ATTRVAL ON CT_89 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_90 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_90_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_90_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_90_DNID ON CT_90 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_90_ATTRVAL ON CT_90 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_91 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_91_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_91_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_91_DNID ON CT_91 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_91_ATTRVAL ON CT_91 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_92 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_92_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_92_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_92_DNID ON CT_92 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_92_ATTRVAL ON CT_92 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_93 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_93_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_93_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_93_DNID ON CT_93 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_93_ATTRVAL ON CT_93 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_94 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_94_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_94_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_94_DNID ON CT_94 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_94_ATTRVAL ON CT_94 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_95 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_95_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_95_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_95_DNID ON CT_95 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_95_ATTRVAL ON CT_95 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_96 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_96_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_96_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_96_DNID ON CT_96 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_96_ATTRVAL ON CT_96 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_97 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_97_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_97_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_97_DNID ON CT_97 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_97_ATTRVAL ON CT_97 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_98 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_98_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_98_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_98_DNID ON CT_98 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_98_ATTRVAL ON CT_98 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_99 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_99_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_99_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_99_DNID ON CT_99 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_99_ATTRVAL ON CT_99 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_100 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_100_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_100_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_100_DNID ON CT_100 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_100_ATTRVAL ON CT_100 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_101 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_101_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_101_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_101_DNID ON CT_101 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_101_ATTRVAL ON CT_101 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_102 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_102_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_102_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_102_DNID ON CT_102 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_102_ATTRVAL ON CT_102 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_103 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_103_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_103_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_103_DNID ON CT_103 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_103_ATTRVAL ON CT_103 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_104 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_104_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_104_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_104_DNID ON CT_104 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_104_ATTRVAL ON CT_104 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_105 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_105_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_105_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_105_DNID ON CT_105 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_105_ATTRVAL ON CT_105 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_106 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_106_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_106_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_106_DNID ON CT_106 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_106_ATTRVAL ON CT_106 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_107 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_107_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_107_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_107_DNID ON CT_107 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_107_ATTRVAL ON CT_107 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_108 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_108_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_108_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_108_DNID ON CT_108 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_108_ATTRVAL ON CT_108 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_109 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_109_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_109_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_109_DNID ON CT_109 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_109_ATTRVAL ON CT_109 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_110 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_110_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_110_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_110_DNID ON CT_110 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_110_ATTRVAL ON CT_110 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_111 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_111_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_111_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_111_DNID ON CT_111 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_111_ATTRVAL ON CT_111 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_112 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_112_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_112_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_112_DNID ON CT_112 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_112_ATTRVAL ON CT_112 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_113 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_113_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_113_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_113_DNID ON CT_113 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_113_ATTRVAL ON CT_113 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_114 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_114_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_114_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_114_DNID ON CT_114 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_114_ATTRVAL ON CT_114 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_115 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_115_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_115_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_115_DNID ON CT_115 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_115_ATTRVAL ON CT_115 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_116 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_116_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_116_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_116_DNID ON CT_116 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_116_ATTRVAL ON CT_116 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_117 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_117_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_117_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_117_DNID ON CT_117 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_117_ATTRVAL ON CT_117 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_118 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_118_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_118_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_118_DNID ON CT_118 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_118_ATTRVAL ON CT_118 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_119 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_119_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_119_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_119_DNID ON CT_119 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_119_ATTRVAL ON CT_119 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_120 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_120_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_120_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_120_DNID ON CT_120 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_120_ATTRVAL ON CT_120 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_121 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_121_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_121_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_121_DNID ON CT_121 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_121_ATTRVAL ON CT_121 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_122 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_122_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_122_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_122_DNID ON CT_122 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_122_ATTRVAL ON CT_122 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_123 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_123_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_123_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_123_DNID ON CT_123 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_123_ATTRVAL ON CT_123 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_124 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_124_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_124_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_124_DNID ON CT_124 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_124_ATTRVAL ON CT_124 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_125 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_125_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_125_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_125_DNID ON CT_125 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_125_ATTRVAL ON CT_125 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_126 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_126_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_126_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_126_DNID ON CT_126 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_126_ATTRVAL ON CT_126 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_127 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_127_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_127_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_127_DNID ON CT_127 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_127_ATTRVAL ON CT_127 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_128 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_128_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_128_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_128_DNID ON CT_128 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_128_ATTRVAL ON CT_128 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_129 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_129_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_129_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_129_DNID ON CT_129 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_129_ATTRVAL ON CT_129 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_130 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_130_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_130_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_130_DNID ON CT_130 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_130_ATTRVAL ON CT_130 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_131 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_131_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_131_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_131_DNID ON CT_131 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_131_ATTRVAL ON CT_131 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_132 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_132_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_132_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_132_DNID ON CT_132 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_132_ATTRVAL ON CT_132 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_133 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_133_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_133_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_133_DNID ON CT_133 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_133_ATTRVAL ON CT_133 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_134 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_134_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_134_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_134_DNID ON CT_134 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_134_ATTRVAL ON CT_134 (ATTRVAL, JPS_DN_ENTRYID);

CREATE TABLE CT_135 (
        JPS_ATTRS_ID    NUMBER NOT NULL,
        JPS_DN_ENTRYID  NUMBER NOT NULL,
        ATTRVAL         VARCHAR2(4000),
        CONSTRAINT CT_135_PK PRIMARY KEY (JPS_ATTRS_ID) ENABLE,
        CONSTRAINT CT_135_FK FOREIGN KEY(JPS_ATTRS_ID) REFERENCES JPS_ATTRS(JPS_ATTRS_ID) ON DELETE CASCADE
        ) ;
CREATE INDEX IDX_CT_135_DNID ON CT_135 (JPS_DN_ENTRYID);
CREATE INDEX IDX_CT_135_ATTRVAL ON CT_135 (ATTRVAL, JPS_DN_ENTRYID);
---opss_version upgrade

INSERT INTO JPS_DN (ENTRYID,RDN,PARENTDN) values ('3006', 'cn=auditstore', 'cn=oracleschemaversion,cn=opss,');

UPDATE JPS_ATTRS SET ATTRVAL='11.1.1.7.0' WHERE ATTRNAME='orclProductVersion' AND (ATTRVAL='11.1.1.4.0');

--opss_attrs upgrade

INSERT INTO JPS_ATTRS (JPS_ATTRS_ID,JPS_DN_ENTRYID,ATTRNAME,ATTRVAL) VALUES ('3027', '3006', 'dn', 'cn=AuditStore,cn=OPSS,cn=OracleSchemaVersion');
INSERT INTO JPS_ATTRS (JPS_ATTRS_ID,JPS_DN_ENTRYID,ATTRNAME,ATTRVAL) VALUES ('3028', '3006', 'orclProductVersion', '11.1.1.7.0');
INSERT INTO JPS_ATTRS (JPS_ATTRS_ID,JPS_DN_ENTRYID,ATTRNAME,ATTRVAL) VALUES ('3029', '3006', 'objectclass', 'top');
INSERT INTO JPS_ATTRS (JPS_ATTRS_ID,JPS_DN_ENTRYID,ATTRNAME,ATTRVAL) VALUES ('3030', '3006', 'objectclass', 'orclcontainer');
INSERT INTO JPS_ATTRS (JPS_ATTRS_ID,JPS_DN_ENTRYID,ATTRNAME,ATTRVAL) VALUES ('3031', '3006', 'objectclass', 'orclschemaversion');
INSERT INTO JPS_ATTRS (JPS_ATTRS_ID,JPS_DN_ENTRYID,ATTRNAME,ATTRVAL) VALUES ('3032', '3006', 'cn', 'AuditStore');

---opss_gencatalog upgrade

--set up audit catalog entry
INSERT INTO CT_10 (JPS_DN_ENTRYID, JPS_ATTRS_ID, ATTRVAL) SELECT JPS_DN_ENTRYID, JPS_ATTRS_ID, LOWER(ATTRVAL) FROM JPS_ATTRS WHERE LOWER(ATTRNAME) = 'cn' AND JPS_DN_ENTRYID = 3006;
INSERT INTO CT_13 (JPS_DN_ENTRYID, JPS_ATTRS_ID, ATTRVAL) SELECT JPS_DN_ENTRYID, JPS_ATTRS_ID, LOWER(ATTRVAL) FROM JPS_ATTRS WHERE LOWER(ATTRNAME) = 'objectclass' AND JPS_DN_ENTRYID = 3006;

insert into CT_34 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, attrval from jps_attrs where lower(attrname) = lower('orclOESResourceParentName');
insert into CT_35 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, attrval from jps_attrs where lower(attrname) = lower('orclOESRoleMapping');
insert into CT_36 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, attrval from jps_attrs where lower(attrname) = 'orcljaznpermissiontargetexpr';
insert into CT_37 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, attrval from jps_attrs where lower(attrname) = lower('orclOESPDPAddress');
insert into CT_38 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, attrval from jps_attrs where lower(attrname) = lower('orclOESPDPConfigurationID');
insert into CT_39 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, attrval from jps_attrs where lower(attrname) = lower('orclOESDistributionID');
insert into CT_40 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, attrval from jps_attrs where lower(attrname) = lower('orclOESDistributionStartTime');
insert into CT_41 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, attrval from jps_attrs where lower(attrname) = lower('orclOESDistributionEndTime');
insert into CT_42 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, attrval from jps_attrs where lower(attrname) = lower('OrclJpsAllResourceActionKeyword');
insert into CT_43 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesprincconstraint';
insert into CT_44 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesresconstraint';
insert into CT_45 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesactionconstraint';
insert into CT_46 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesenvconstraint';
insert into CT_47 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, attrval from jps_attrs where lower(attrname) = 'orcloespolicyref';
insert into CT_48 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, attrval from jps_attrs where lower(attrname) = 'orcloespolicysetref';
insert into CT_49 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloespolicyissuer';
insert into CT_50 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloespolicyversion';
insert into CT_51 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesallowadviceref';
insert into CT_52 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesdenyadviceref';
insert into CT_53 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesdenyobligationref';
insert into CT_54 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloespolicycombiningalgorithmref';
insert into CT_55 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesrulecombiningalgorithmref';
insert into CT_56 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcljpsallresourckeyword';
insert into CT_57 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, attrval from jps_attrs where lower(attrname) = 'orcljpsresourcematchingalgorithm';
insert into CT_58 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcljpsresourcenameexpression';
insert into CT_59 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcljpsroletype';
insert into CT_60 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'givenname';
insert into CT_61 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcoesappattributes';
insert into CT_62 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcljpsresourceexpression';
insert into CT_63 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcljpsresourcelocalityref';
insert into CT_64 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcljpssuperresourcetype';
insert into CT_65 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesactcollectionname';
insert into CT_66 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesactcollectionrfs';
insert into CT_67 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesattributecollectionhandlerfunctionname';
insert into CT_68 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesattributecollectionhandlerpackagename';
insert into CT_69 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesattributecollectionhandlerschemaname';
insert into CT_70 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesattributecollectionname';
insert into CT_71 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesdscolumnattrs';
insert into CT_72 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesdsprimkey';
insert into CT_73 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesdatasourcectrnt';
insert into CT_74 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesdatasourcename';
insert into CT_75 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesdatasourcetype';
insert into CT_76 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesdefaultpolsetref';
insert into CT_77 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesissensitive';
insert into CT_78 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloespolicycategory';
insert into CT_79 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloespolicyextension';
insert into CT_80 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloespolicysetcategory';
insert into CT_81 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloespolicysettype';
insert into CT_82 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloespolicytype';
insert into CT_83 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesrestypecategory';
insert into CT_84 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesresourcehirchytype';
insert into CT_85 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesresourcenamedelim';
insert into CT_86 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloessqlexpression';
insert into CT_87 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloestargetexpression';
insert into CT_88 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesxmlexpression';
insert into CT_89 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcldistributionversion';
insert into CT_90 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesallresourcetype';
insert into CT_91 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orclactiveenddate';
insert into CT_92 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orclactivestartdate';
insert into CT_93 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcljpsextensiontype';
insert into CT_94 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcljpsresourceconverter';
insert into CT_95 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcljpsresourcematchingalg';
insert into CT_96 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcljpsobjguid';
insert into CT_97 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcljpspolicydomainname';
insert into CT_98 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcljpsresourcetypeactionattrs';
insert into CT_99 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcljpsrolememberexpression';
insert into CT_100 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesactionattributes';
insert into CT_101 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesalgorithmjavaclass';
insert into CT_102 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesattributeissuer';
insert into CT_103 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesattributenamespace';
insert into CT_104 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesattributetype';
insert into CT_105 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloescombinerparameter';
insert into CT_106 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesdistributionissuer';
insert into CT_107 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesenvattributes';
insert into CT_108 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesexecutionfrequency';
insert into CT_109 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesexpression';
insert into CT_110 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesfunctioncategory';
insert into CT_111 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesfunctionclass';
insert into CT_112 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesfunctionparameters';
insert into CT_113 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesfunctionreturntype';
insert into CT_114 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesissinglevalued';
insert into CT_115 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesmatchinfo';
insert into CT_116 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesmaxdelegationdepth';
insert into CT_117 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesobligationfulfillon';
insert into CT_118 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloespdpinstancename';
insert into CT_119 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloespdpstatussuccess';
insert into CT_120 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloespiptype';
insert into CT_121 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloespolicycombinerparameter';
insert into CT_122 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloespolicydefaults';
insert into CT_123 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloespolicyruleorder';
insert into CT_124 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloespolicysetdefaults';
insert into CT_125 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloespresencerequired';
insert into CT_126 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesprincipalattributes';
insert into CT_127 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesresourceattributes';
insert into CT_128 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesrulecombinerparameter';
insert into CT_129 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloessetcombinerparameter';
insert into CT_130 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloessetmemberorder';
insert into CT_131 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesimpliedactions';
insert into CT_132 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesmetadatafinder';
insert into CT_133 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesattributecollectionattributes';
insert into CT_134 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orcloesattributecollectioneventtype';
insert into CT_135 (jps_dn_entryid, jps_attrs_id, attrval) select jps_dn_entryid, jps_attrs_id, lower(attrval) from jps_attrs where lower(attrname) = 'orclenabled';
COMMIT;
