<wsdl:definitions name="Cust-DetailsWS" targetNamespace="http://www.example.org/Cust-DetailsWS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.example.org/Cust-DetailsWS/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns1="http://www.example.org/Cust-Details1">
  <wsdl:types>
   <xsd:schema>
      <xsd:import namespace="http://www.example.org/Cust-Details1" schemaLocation="../XSD/Cust-Details.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="NewOperationRequest">
    <wsdl:part element="tns1:EmpRequest" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="NewOperationResponse">
    <wsdl:part element="tns1:EmpResp" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="Cust-DetailsWS">
    <wsdl:operation name="NewOperation">
      <wsdl:input message="tns:NewOperationRequest"/>
      <wsdl:output message="tns:NewOperationResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="Cust-DetailsWSSOAP" type="tns:Cust-DetailsWS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="NewOperation">
      <soap:operation soapAction="http://www.example.org/Cust-DetailsWS/NewOperation"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Cust-DetailsWS">
    <wsdl:port binding="tns:Cust-DetailsWSSOAP" name="Cust-DetailsWSSOAP">
      <soap:address location="http://www.example.org/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>