# ARCS: $Header: /home/cvs/cvs/RDA_4/src/scripting/lib/modules/modules.pod,v 2.51 2012/09/03 06:05:14 mschenke Exp $

=head1 NAME

modules - Oracle Remote Diagnostic Agent Module List

=head1 DATA COLLECTION MODULES

=over 7

=item o S<B<L<ACFS|modules::S403ACFS>>> Collects ASM Cluster File System
Information

=item o S<B<L<ACT|modules::S500ACT> >> Collects Oracle E-Business Suite
Application Information

=item o S<B<L<ADBA|modules::S700ADBA>>> Collects ACS Oracle Database Assessment

=item o S<B<L<ADX|modules::S510ADX> >> Collects AutoConfig and Rapid Clone
Information

=item o S<B<L<AGT|modules::S420AGT> >> Collects Enterprise Manager Agent
Information

=item o S<B<L<APEX|modules::S292APEX>>> Collects APEX Information

=item o S<B<L<ASAP|modules::S484ASAP>>> Collects Oracle Communications
Automated Service Activation Program

=item o S<B<L<ASBR|modules::S305ASBR>>> Collects Oracle Application Server
Backup and Recovery Information

=item o S<B<L<ASG|modules::S306ASG> >> Collects Application Server Guard
Information

=item o S<B<L<ASIT|modules::S313ASIT>>> Collects Oracle Application Server 11g
Installation Information

=item o S<B<L<ASM|modules::S402ASM> >> Collects Automatic Storage Management
Information

=item o S<B<L<B2B|modules::S375B2B> >> Collects Oracle Business to Business
Information

=item o S<B<L<BAM|modules::S374BAM> >> Collects Business Activity Monitoring
Information

=item o S<B<L<BEE|modules::S250BEE> >> Collects Beehive Information

=item o S<B<L<BI|modules::S397BI> > > Collects Business Intelligence Enterprise
Edition Information

=item o S<B<L<BIPL|modules::S399BIPL>>> Collects Oracle Business Intelligence
Publisher Information

=item o S<B<L<BPEL|modules::S373BPEL>>> Collects Oracle BPEL Process Manager
Information

=item o S<B<L<BPM|modules::S376BPM> >> Collects Oracle Business Process
Management Suite Information

=item o S<B<L<BR|modules::S205BR> > > Collects Oracle Database Backup/Recovery
Information

=item o S<B<L<BRM|modules::S380BRM> >> Collects Oracle Communication Billing
and Revenue Management

=item o S<B<L<CAMM|modules::S377AMM>>> Collects Oracle Composite Application
Monitor and Modeler Information

=item o S<B<L<CB|modules::S585CB> > > Collects Oracle Crystal Ball Information

=item o S<B<L<CCR|modules::S910CCR>> > Collects OCM Diagnostic Information

=item o S<B<L<CFG|modules::S010CFG>> > Collects Key Configuration Information

=item o S<B<L<CM|modules::S489CM> > > Collects Oracle Communications
Configuration Management Information

=item o S<B<L<COHR|modules::S365COHR>>> Collects Oracle Coherence Information

=item o S<B<L<CONT|modules::S248CONT>>> Collects Oracle Content Services
Information

=item o S<B<L<CRID|modules::S360CRID>>> Collects Oracle Access Manager (COREid)
Information

=item o S<B<L<CS|modules::S495CS> > > Collects Oracle Communications Calendar
Server Information

=item o S<B<L<CUST|modules::S997CUST>>> Collects Customer-Specific Information

=item o S<B<L<D2PC|modules::S207D2PC>>> Collects Distributed Transaction
Information

=item o S<B<L<DAC|modules::S398DAC> >> Collects Oracle Business Intelligence
Data Warehouse Administration Console Information

=item o S<B<L<DB|modules::S200DB> > > Controls Oracle RDBMS Data Collection

=item o S<B<L<DBA|modules::S201DBA> >> Collects Oracle RDBMS Information

=item o S<B<L<DBC|modules::S430DBC> >> Collects Database Control Information

=item o S<B<L<DBM|modules::S203DBM> >> Collects Oracle RDBMS Memory Information

=item o S<B<L<DEV|modules::S290DEV> >> Collects Oracle Developer Information

=item o S<B<L<DG|modules::S405DG> > > Collects Data Guard Information

=item o S<B<L<DNFS|modules::S212DNFS>>> Collects Direct NFS Information

=item o S<B<L<DPS|modules::S346DPS> >> Collects Oracle DSEE Directory Proxy
Server Information

=item o S<B<L<DSCS|modules::S246DSCS>>> Collects Discussions Information

=item o S<B<L<DSCV|modules::S390DSCV>>> Collects Oracle Discoverer Information

=item o S<B<L<ECM|modules::S352ECM> >> Controls Oracle Enterprise Content
Management 11g Data Collection

=item o S<B<L<EM|modules::S440EM> > > Collects Enterprise Manager OMS and
Repository Information

=item o S<B<L<EMS|modules::S531EMS> >> Collects Email Marketing Server
Information

=item o S<B<L<END|modules::S999END> >> Finalizes the Data Collection

=item o S<B<L<EPM|modules::S545EPM> >> Collects Enterprise Performance
Management System Information

=item o S<B<L<EPMA|modules::S572EPMA>>> Collects Enterprise Performance
Management Architect Information

=item o S<B<L<ES|modules::S344ES> > > Collects Oracle Entitlements Server
Information

=item o S<B<L<ESB|modules::S371ESB> >> Collects Enterprise Service Bus
Information

=item o S<B<L<ESS|modules::S550ESS> >> Collects Oracle Essbase Information

=item o S<B<L<ESSO|modules::S332ESSO>>> Collects Oracle Enterprise Single
Sign-On (PassLogix) Information

=item o S<B<L<EXA|modules::S280EXA> >> Collects Exadata Information

=item o S<B<L<EXL|modules::S315EXL> >> Collects Oracle Exalogic Information

=item o S<B<L<FCM|modules::S565FCM> >> Collects Oracle Hyperion Financial Close
Management Information

=item o S<B<L<FLTR|modules::S990FLTR>>> Controls Report Content Filtering

=item o S<B<L<GFS|modules::S316GFS> >> Collects Oracle GlassFish Server
Information

=item o S<B<L<GRDN|modules::S450GRDN>>> Collects Oracle Guardian Information

=item o S<B<L<GRID|modules::S410GRID>>> Controls Grid Control Data Collection

=item o S<B<L<GTW|modules::S125GTW> >> Collects Transparent/Procedural Gateway
Information

=item o S<B<L<HCM|modules::S566HCM> >> Collects Hyperion Calculation Manager
Information

=item o S<B<L<HDRM|modules::S578HDRM>>> Collects Hyperion Data Relationship
Management Information

=item o S<B<L<HFM|modules::S564HFM> >> Collects Hyperion Financial Management
Information

=item o S<B<L<HFR|modules::S557HFR> >> Collects Hyperion Financial Reporting
Information

=item o S<B<L<HIR|modules::S555HIR> >> Collects Oracle Hyperion Interactive
Reporting Information

=item o S<B<L<HPL|modules::S563HPL> >> Collects Hyperion Planning Information

=item o S<B<L<HPSV|modules::S554HPSV>>> Collects Oracle Hyperion Provider
Services Information

=item o S<B<L<HSS|modules::S571HSS> >> Collects Oracle Hyperion Shared Services
Information

=item o S<B<L<HSV|modules::S573HSV> >> Collects Oracle Hyperion Smart View for
Office Information

=item o S<B<L<IA|modules::S220IA> > > Collects Intelligent Agent Information

=item o S<B<L<IAS|modules::S300IAS> >> Collects Web Server Information

=item o S<B<L<IFS|modules::S320IFS> >> Collects iFS (iFS, CMSDK, Files)
Information

=item o S<B<L<INFA|modules::S396INFA>>> Collects Informatica Information

=item o S<B<L<INI|modules::S000INI> >> Initializes the Data Collection

=item o S<B<L<INST|modules::S130INST>>> Collects the Oracle Installation
Information

=item o S<B<L<IPM|modules::S355IPM> >> Collects Oracle Imaging and Process
Management Information

=item o S<B<L<IPSA|modules::S486IPSA>>> Collects Oracle Communications
IP Service Activator Information

=item o S<B<L<IWPS|modules::S318IWPS>>> Collects Oracle iPlanet Web Proxy
Server Information

=item o S<B<L<IWS|modules::S317IWS> >> Collects Oracle iPlanet Web Server
Information

=item o S<B<L<J2EE|modules::S310J2EE>>> Collects J2EE Standalone Information

=item o S<B<L<JDBC|modules::S366JDBC>>> Collects Oracle Java DB connectivity
(JDBC) Information

=item o S<B<L<JDEV|modules::S367JDEV>>> Collects Oracle JDeveloper Information

=item o S<B<L<JIVE|modules::S326JIVE>>> Collects Jive Information

=item o S<B<L<LANG|modules::S294LANG>>> Collects Oracle Language Information

=item o S<B<L<LOAD|modules::S919LOAD>>> Produces the External Collection
Reports

=item o S<B<L<LOG|modules::S204LOG> >> Collects Oracle Database Trace and Log
Files

=item o S<B<L<MAIL|modules::S241MAIL>>> Collects Oracle Collaboration Suite
Mail Information

=item o S<B<L<MES|modules::S494MES> >> Collects Oracle Messaging Exchange
Server Information

=item o S<B<L<MSLG|modules::S295MSLG>>> Collects Microsoft Languages
Information

=item o S<B<L<MYCL|modules::S239MYCL>>> Collects Oracle MySQL Cluster
Information

=item o S<B<L<MYSQ|modules::S237MYSQ>>> Collects Oracle MySQL Server Information

=item o S<B<L<NCC|modules::S491NCC> >> Collects Network Charging and Control
Information

=item o S<B<L<ND|modules::S482ND> > > Collects Oracle Communications Network
Discovery Information

=item o S<B<L<NET|modules::S120NET> >> Collects Network Information

=item o S<B<L<NI|modules::S483NI> > > Collects Oracle Communications Network
Integrity Information

=item o S<B<L<NM|modules::S480NM> > > Collects Oracle Communications Network
Mediation Information

=item o S<B<L<NPRF|modules::S800NPRF>>> Samples Performance Information (root
not required)

=item o S<B<L<OAAM|modules::S363OAAM>>> Collects Oracle Adaptive Access Manager
Information

=item o S<B<L<OAM|modules::S361OAM> >> Collects Oracle Access Manager Information

=item o S<B<L<OCAL|modules::S244OCAL>>> Collects Oracle Calendar Information

=item o S<B<L<OCDB|modules::S236OCDB>>> Collects Oracle Content Database
Information

=item o S<B<L<OCFS|modules::S401OCFS>>> Collects Oracle Cluster File System
Information

=item o S<B<L<OCM|modules::S090OCM> >> Setting up Configuration Manager
Interface

=item o S<B<L<OCS|modules::S240OCS> >> Controls Oracle Collaboration Suite Data
Collection

=item o S<B<L<ODC|modules::S357ODC> >> Collects Oracle Document Capture
Information

=item o S<B<L<ODI|modules::S385ODI> >> Collects Oracle Data Integrator
Information

=item o S<B<L<ODM|modules::S392ODM> >> Collects Oracle Data Mining Information

=item o S<B<L<OES|modules::S215OES> >> Collects Oracle Express Server
Information

=item o S<B<L<OFA|modules::S600OFA> >> Collects Oracle Fusion Applications
Information

=item o S<B<L<OGG|modules::S394OGG> >> Collects Oracle GoldenGate Information

=item o S<B<L<OIA|modules::S347OIA> >> Collects Oracle Identity Analytics
Information

=item o S<B<L<OID|modules::S340OID> >> Collects Oracle Internet Directory
Information

=item o S<B<L<OIF|modules::S364OIF> >> Collects Oracle Identity Federation
Information

=item o S<B<L<OIM|modules::S362OIM> >> Collects Oracle Identity Manager
Information

=item o S<B<L<OLAP|modules::S210OLAP>>> Collects OLAP Information

=item o S<B<L<OMM|modules::S208OMM> >> Collects Oracle Multimedia or Oracle
interMedia Information

=item o S<B<L<ONET|modules::S122ONET>>> Collects Oracle Net Information

=item o S<B<L<OS|modules::S100OS> > > Collects the Operating System Information

=item o S<B<L<OSB|modules::S378OSB> >> Collects Oracle Service Bus Information

=item o S<B<L<OSM|modules::S487OSM> >> Collects Oracle Communications Order and
Service Management Information

=item o S<B<L<OSSO|modules::S319OSSO>>> Collects Oracle OpenSSO Information

=item o S<B<L<OUD|modules::S343OUD> >> Collects Oracle Unified Directory
Information

=item o S<B<L<OVD|modules::S342OVD> >> Collects Oracle Virtual Directory
Information

=item o S<B<L<OVMM|modules::S142OVMM>>> Collects Oracle VM Manager Information

=item o S<B<L<OVMS|modules::S140OVMS>>> Collects Oracle VM Server Information

=item o S<B<L<OW|modules::S348OW> > > Collects Oracle Waveset Information

=item o S<B<L<OWB|modules::S391OWB> >> Collects Oracle Warehouse Builder
Information

=item o S<B<L<OWSM|modules::S372OWSM>>> Collects Oracle Web Services Manager
Information

=item o S<B<L<PDA|modules::S325PDA> >> Collects Portal Diagnostics Information

=item o S<B<L<PAPP|modules::S728PAPP>>> Collects PeopleSoft Information from
Tuxedo Application Server

=item o S<B<L<PDBA|modules::S725PDBA>>> Collects PeopleSoft Information from
Oracle Database

=item o S<B<L<PDC|modules::S492PDC> >> Collects Oracle Communications Pricing
Design Center Information

=item o S<B<L<PERF|modules::S110PERF>>> Collects Performance Information

=item o S<B<L<PLNC|modules::S298PLNC>>> Collects Oracle PL/SQL Native
Compilation Information

=item o S<B<L<PR|modules::S556PR> > > Collects Oracle Hyperion SQR
Production Reporting Information

=item o S<B<L<PROF|modules::S105PROF>>> Collects the User Profile

=item o S<B<L<PS|modules::S488PS> > > Collects Oracle Communications Policy
Services Information

=item o S<B<L<PSCH|modules::S729PSCH>>> Collects PeopleSoft Information from
Process scheduler

=item o S<B<L<PSFT|modules::S720PSFT>>> Controls PeopleSoft Data Collections

=item o S<B<L<PWEB|modules::S730PWEB>>> Collects PeopleSoft Information from
Web Application Server

=item o S<B<L<RAC|modules::S400RAC> >> Collects Cluster Information

=item o S<B<L<RACD|modules::S400RACD>>> Performs a Oracle Database Hang Analysis

=item o S<B<L<RDSP|modules::S909RDSP>>> Produces the Remote Data Collection
Reports

=item o S<B<L<RET|modules::S590RET> >> Collects Oracle Retail Information

=item o S<B<L<REXE|modules::S900REXE>>> Performs the Remote Data Collections

=item o S<B<L<RPRF|modules::S801RPRF>>> Samples Performance Information (root
privileges required)

=item o S<B<L<RSRC|modules::S206RSRC>>> Collects Oracle Database Resource
Manager
Information

=item o S<B<L<RTC|modules::S245RTC> >> Collects Real Time Communication
Information

=item o S<B<L<SEBL|modules::S530SEBL>>> Collects Siebel Information

=item o S<B<L<SES|modules::S335SES> >> Collects Oracle Secure Enterprise Search
Information

=item o S<B<L<SMPL|modules::S020SMPL>>> Controls Sampling

=item o S<B<L<SOA|modules::S370SOA> >> Collects Oracle SOA Suite Information

=item o S<B<L<SP|modules::S213SP> > > Collects SQL*Plus/iSQL*Plus Information

=item o S<B<L<SSO|modules::S330SSO> >> Collects Single Sign-On Information

=item o S<B<L<STC|modules::S230STC> >> Collects Streams Configuration
Information

=item o S<B<L<STA|modules::S369STA> >> Collects StorageTek Tape Analytics
Information

=item o S<B<L<STM|modules::S231STM> >> Collects Streams Monitoring Information

=item o S<B<L<TOPL|modules::S368TOPL>>> Collects Oracle TopLink Information

=item o S<B<L<TTEN|modules::S235TTEN>>> Collects Oracle TimesTen In-Memory
Database Information

=item o S<B<L<TUX|modules::S321TUX> >> Collects Oracle Tuxedo Information

=item o S<B<L<UCM|modules::S354UCM> >> Collects Oracle Universal Content
Management Information

=item o S<B<L<UIM|modules::S490UIM> >> Collects Oracle Oracle Communications
Unified Inventory Management Information

=item o S<B<L<UOA|modules::S353UOA> >> Collects Oracle Universal Online Archive
11g Information

=item o S<B<L<WAC|modules::S242WAC> >> Collects Web Access Client Information

=item o S<B<L<WC|modules::S328WC> > > Collects Oracle WebCenter Information

=item o S<B<L<WCA|modules::S328WCA> >> Collects Oracle WebCenter Analytics
Information

=item o S<B<L<WCI|modules::S328WCI> >> Collects Oracle WebCenter Interaction
Information

=item o S<B<L<WEBC|modules::S350WEBC>>> Collects Web Cache Information

=item o S<B<L<WKSP|modules::S247WKSP>>> Collects Workspaces Information

=item o S<B<L<WLI|modules::S379WLI>> > Collects Oracle WebLogic Integration
Information

=item o S<B<L<WLS|modules::S301WLS> >> Collects Oracle WebLogic Server
Information

=item o S<B<L<WMC|modules::S243WMC> >> Collects Webmail Client Information

=item o S<B<L<WRLS|modules::S249WRLS>>> Collects Wireless Information

=item o S<B<L<WSP|modules::S302WSP> >> Collects IBM WebSphere Application
Server Information

=item o S<B<L<XDB|modules::S209XDB> >> Collects XDB Information

=item o S<B<L<XSMP|modules::S898XSMP>>> Samples User Defined Data

=item o S<B<L<XTRA|modules::S998XTRA>>> Collects User Defined Data

=back

=head1 TOOLS

Run the following modules with the B<-T> mode option

=over 9

=item o S<B<L<diff|modules::TLdiff> > > Compares Systems

=item o S<B<L<emp|modules::TLepm>> B< > > Collects Enterprise Performance
Management Validation Information

=item o S<B<L<hcve|modules::TSThcve> > > Executes HCVE Tests

=item o S<B<L<jrockt|modules::TLjrockt>>> Collects Oracle JRockit Process
Information

=item o S<B<L<merge|modules::TLmerge>> > Merges Alert Log and Trace Files

=item o S<B<L<na|modules::TLna> > B< > > Runs the Network Advisor

=item o S<B<L<ora600|modules::TLora600>>> Diagnoses ORA-600 Oracle Internal
Errors

=item o S<B<L<oraddc|modules::TLoraddc>>> Runs the Oracle Database Diagnostic
Collector

=item o S<B<L<root|modules::TLroot> > > Collects System Log and Executes
Commands as root User

=item o S<B<L<secure|modules::TLsecure>>> Identifies Potential Security Risks

=item o S<B<L<siebel|modules::TLsiebel>>> Collects Siebel Crash Information

=item o S<B<L<sos|modules::TLsos>> B< > > Collects siga/sosreport/sysreport
Report

=back

=head1 TEST MODULES

Run the following modules with the B<-T> mode option

=over 9

=item o S<B<L<alert|modules::TSTalert>>> Analyzes alert.log

=item o S<B<L<cell|modules::TSTcell>> > Tests Connection to Exadata Cells

=item o S<B<L<core|modules::TSTcore>> > Tests Stack Trace Extraction

=item o S<B<L<db|modules::TSTdb>> B< > > Tests Local Oracle Database Access

=item o S<B<L<dbi|modules::TSTdbi> > > Tests Oracle Database Access Using the
Database Interface

=item o S<B<L<dst|modules::TSTdst> > > Daylight Saving Time Tool Box

=item o S<B<L<env|modules::TSTenv> > > Tests the Environment

=item o S<B<L<event|modules::TSTevent>>> Extracts Event Log Information

=item o S<B<L<exl|modules::TSTexl> > > Tests Connection to Oracle Exalogic Nodes

=item o S<B<L<inv|modules::TSTinv> > > Tests Oracle Home Inventory Content

=item o S<B<L<ocm|modules::TSTocm> > > Tests Configuration Manager Discovery
Information

=item o S<B<L<odbc|modules::TSTodbc>> > Tests Oracle Database Access Using ODBC

=item o S<B<L<odi|modules::TSTodi> > > Displays the Current Oracle Data
Integrator Module Setup

=item o S<B<L<sql|modules::TSTsql> > > Tests SQL Settings

=item o S<B<L<ssd|modules::TSTssd> > > Analyzes System State Dumps

=item o S<B<L<ssh|modules::TSTssh> > > Tests Remote Connectivity and Operations

=item o S<B<L<vms|modules::TSTvms> > > Verifies Current User Environment for VMS

=back

=head1 COPYRIGHT NOTICE

Copyright (c) 2002, 2012, Oracle and/or its affiliates. All rights reserved.

=head1 TRADEMARK NOTICE

Oracle and Java are registered trademarks of Oracle and/or its
affiliates. Other names may be trademarks of their respective owners.

=cut
