# ARCS: $Header: /home/cvs/cvs/RDA_4/src/scripting/lib/modules/profiles.pod,v 2.43 2012/07/29 20:37:11 mschenke Exp $

=head1 NAME

profiles - Oracle Remote Diagnostic Agent Setup Profiles

=head1 PROFILE DEFINITION

A setup profile consists of a list of data collection modules and predefined
settings. Therefore, the data collected using a profile can be slightly
different than using the module separately. Profiles are typically used to
set up all modules required to diagnose a specific class of problems.

Profile names are case sensitive.

=head1 USING A PROFILE

In this page, E<lt>rdaE<gt> represents the command you selected to run RDA (for
example, F<rda.pl>, F<rda.cmd>, F<rda.sh>, and C<perl rda.pl>).

When profiles are not used, RDA considers all existing modules by default. To
set up the data collection with a profile, use the following command:

<rda> -S -p <profile_name>

Run the data collection as usual. If you want to perform all steps in a single
run, then use a command such as the following:

<rda> -vdSCRP -p <profile_name>

You can combine profiles with other options. For example, specify an
alternative setup file location as follows:

<rda> -vdSCRP -s $HOME/rda/system1 -p <profile_name>

Note: The F<$HOME/rda> directory must exist and it is used as the default
location for the report directory also.

While a profile remains the current profile, its setting values can
override other default values each time the setup is performed. To avoid this
behavior, you can switch to the C<Default> profile, by using a command similar
to the following:

<rda> -S -p Default

To obtain a list of available profile names and their applicability, use the
following command:

<rda> -L profiles

To view this manual page, enter the following:

<rda> -M profiles

To view the manual page of a profile, enter the following:

<rda> -M -p <profile_name>

Add the B<-f> option to include the list of settings assigned by the profile.

<rda> -fM -p <profile_name>

To obtain the modules and profiles cross reference, enter the following:

<rda> -x profiles

=head2 Setting Level Definitions

Only a minimum set of settings are prompted by default. To fine-tune the data
collection, run the profile with the C<advanced> setting level. For
example:

<rda> -S -p advanced DB

This setting level is stored in the setup file. Therefore, if you have to
change the setting level, then run the profile again as follows:

<rda> -S -p basic CFG

To obtain the list of all setting levels, enter the following:

<rda> -L levels

=head2 Combining Setting Level and Profile

You can combine setting levels and profiles by concatenating them with 
a hyphen (-) sign. You can specify them in any order.

<rda> -S -p AS10g-advanced

As mentioned above, the setting level is saved in the setup file and is reused
by default in the next setup operations, including when configuring extra
modules.

=head2 Custom Profiles Definitions

These explanations assume that you are using the default profile definition
file. You can define the location of a custom profile definition with an
C<RDA_PROFILE> environment variable.

=head1 PROFILE APPLICABILITY

=over 24

=item o B<L<9iAS|profile::9iAS>>

Oracle Application Server 9i-related problems

=item o B<L<AS10g|profile::AS10g>>

Oracle Application Server 10g-related problems

=item o B<L<AS10g_FormsReports|profile::AS10g_FormsReports>>

Oracle Forms/Reports 10g-related problems

=item o B<L<AS10g_Identity|profile::AS10g_Identity>>

Oracle Application Server 10g Identity Management-related problems

=item o B<L<AS10g_IdentityFed|profile::AS10g_IdentityFed>>

Oracle Application Server 10g Identity Federation-related problems

=item o B<L<AS10g_MidTier|profile::AS10g_MidTier>>

Oracle Application Server 10g middle tier-related problems

=item o B<L<AS10g_Repository|profile::AS10g_Repository>>

Oracle Application Server 10g metadata repository-related problems

=item o B<L<AS10g_WebTier|profile::AS10g_WebTier>>

Oracle Application Server 10g WebTier-related problems

=item o B<L<AS_BackupRecovery|profile::AS_BackupRecovery>>

Oracle Application Server backup and recovery-related problems

=item o B<L<Act|profile::Act>>

Oracle Applications overview

=item o B<L<AppsCheck|profile::AppsCheck>>

Equivalent to Appscheck

=item o B<L<Apps_DB_Assessment|profile::Apps_DB_Assessment>>

Oracle Applications Database assessment collections

=item o B<L<Asm_Assessment|profile::Asm_Assessment>>

Oracle ASM assessment collections

=item o B<L<AsmFileSystem|profile::AsmFileSystem>>

Oracle ASM Cluster File System-related problems

=item o B<L<Bam|profile::Bam>>

Business Activity Monitoring-related problems

=item o B<L<Beehive|profile::Beehive>>

Oracle Beehive-related problems

=item o B<L<CloudControl12c|profile::CloudControl12c>>

Cloud Control 12c-related problems

=item o B<L<ClusterFileSystem|profile::ClusterFileSystem>>

Oracle Cluster File System-related problems

=item o B<L<Com_ASAP|profile::Com_ASAP>>

Oracle Communications ASAP problems

=item o B<L<Com_CM|profile::Com_CM>>

Oracle Communications Configuration Manager problems

=item o B<L<Com_IPSA|profile::Com_IPSA>>

Oracle Communications IPSA Software problems

=item o B<L<Com_NCC|profile::Com_NCC>>

Oracle Communications Network Charging and Control problems

=item o B<L<Com_ND|profile::Com_ND>>

Oracle Communications Network Discovery problems

=item o B<L<Com_NI|profile::Com_NI>>

Oracle Communications Network Integrity problems

=item o B<L<Com_NM|profile::Com_NM>>

Oracle Communications Network Mediation problems

=item o B<L<Com_OSM|profile::Com_OSM>>

Oracle Communications Order and Service Management problems

=item o B<L<Com_PS|profile::Com_PS>>

Oracle Communications Policy Services problems

=item o B<L<Com_UIM|profile::Com_UIM>>

Oracle Communications Unified Inventory Management problems

=item o B<L<DataGuard|profile::DataGuard>>

Oracle Data Guard-related problems

=item o B<L<DB8i|profile::DB8i>>

Oracle Database 8i-related problems

=item o B<L<DB9i|profile::DB9i>>

Oracle Database 9i-related problems

=item o B<L<DB10g|profile::DB10g>>

Oracle Database 10g-related problems

=item o B<L<DB11g|profile::DB11g>>

Oracle Database 11g-related problems

=item o B<L<DB_Assessment|profile::DB_Assessment>>

Oracle Database assessment collections

=item o B<L<DB_BackupRecovery|profile::DB_BackupRecovery>>

Oracle Database backup and recovery-related problems

=item o B<L<DB_Perf|profile::DB_Perf>>

Oracle Database performance problems

=item o B<L<DirectNFS|profile::DirectNFS>>

Direct NFS-related problems

=item o B<L<Discoverer10g|profile::Discoverer10g>>

Oracle Discoverer 10g-related problems

=item o B<L<Discoverer11g|profile::Discoverer11g>>

Oracle Discoverer 11g-related problems

=item o B<L<EPMA_FullRun|profile::EPMA_FullRun>>

Oracle Enterprise Performance Management Architect-related problems

=item o B<L<EnterpriseSearch|profile::EnterpriseSearch>>

Oracle Secure Enterprise Search-related problems

=item o B<L<Essbase|profile::Essbase>>

Oracle Essbase-related problems

=item o B<L<Exadata_Assessment|profile::Exadata_Assessment>>

Oracle Exadata assessment collections

=item o B<L<Exadata_CellBrownout|profile::Exadata_CellBrownout>>

Oracle Exadata long brownout due to cell failure-related problems

=item o B<L<Exadata_CellFailure|profile::Exadata_CellFailure>>

Oracle Exadata cell failure-related problems

=item o B<L<Exadata_DatabaseCrash|profile::Exadata_DatabaseCrash>>

Oracle Exadata database crash-related problems

=item o B<L<Exadata_DatabaseHang|profile::Exadata_DatabaseHang>>

Oracle Exadata database hang-related problems

=item o B<L<Exadata_FailedDrives|profile::Exadata_FailedDrives>>

Oracle Exadata failed drives-related problems

=item o B<L<Exadata_FlashDrives|profile::Exadata_FlashDrives>>

Oracle Exadata flash drives-related problems

=item o B<L<Exadata_IbSwitch|profile::Exadata_IbSwitch>>

Oracle Exadata InfiniBand switch-related problems

=item o B<L<Exadata_Ilom|profile::Exadata_Ilom>>

Oracle Exadata Integrated Lights Out Manager-related problems

=item o B<L<Exadata_ListenerHang|profile::Exadata_ListenerHang>>

Oracle Exadata listener hang-related problems

=item o B<L<Exadata_Network|profile::Exadata_Network>>

Oracle Exadata general network-related problems

=item o B<L<Exadata_NetworkCable|profile::Exadata_NetworkCable>>

Oracle Exadata network cabling-related problems

=item o B<L<Exadata_RacInstance|profile::Exadata_RacInstance>>

Oracle Exadata RAC instance-related problems

=item o B<L<Exadata_SickCell|profile::Exadata_SickCell>>

Oracle Exadata sick cell-related problems

=item o B<L<Exalogic_DriveFailure|profile::Exalogic_DriveFailure>>

Oracle Exalogic drive failure-related problems

=item o B<L<Exalogic_Gateway|profile::Exalogic_Gateway>>

Oracle Exalogic gateway-related problems

=item o B<L<Exalogic_HealthHwSw|profile::Exalogic_HealthHwSw>>

Oracle Exalogic hardware and software health-related problems

=item o B<L<Exalogic_HealthNet|profile::Exalogic_HealthNet>>

Oracle Exalogic network health-related problems

=item o B<L<Exalogic_IbFabric|profile::Exalogic_IbFabric>>

Oracle Exalogic IB fabric-related problems

=item o B<L<Exalogic_IbSwitch|profile::Exalogic_IbSwitch>>

Oracle Exalogic IB switch-related problems

=item o B<L<Exalogic_Ilom|profile::Exalogic_Ilom>>

Oracle Exalogic ILOM-related problems

=item o B<L<Exalogic_Network|profile::Exalogic_Network>>

Oracle Exalogic general network-related problems

=item o B<L<Exalogic_Patch|profile::Exalogic_Patch>>

Oracle Exalogic image patches-related problems

=item o B<L<Exalogic_Raid|profile::Exalogic_Raid>>

Oracle Exalogic RAID card-related problems

=item o B<L<Exalogic_Temp|profile::Exalogic_Temp>>

Oracle Exalogic ambient temperature-related problems

=item o B<L<FCM_FullRun|profile::FCM_FullRun>>

Oracle Hyperion Financial Close Management-related problems

=item o B<L<FinancialReporting|profile::FinancialReporting>>

Oracle Hyperion Financial Reporting-related problems

=item o B<L<FM11g_AccessManager|profile::FM11g_AccessManager>>

Oracle Access Manager 11g-related problems

=item o B<L<FM11g_Bi|profile::FM11g_Bi>>

Oracle Business Intelligence Enterprise Edition 11g-related problems

=item o B<L<FM11g_Ecm|profile::FM11g_Ecm>>

Oracle Enterprise Content Management 11g-related problems

=item o B<L<FM11g_FormsReports|profile::FM11g_FormsReports>>

Oracle Forms/Reports 11g-related problems

=item o B<L<FM11g_Identity|profile::FM11g_Identity>>

Oracle Identity Management 11g-related problems

=item o B<L<FM11g_Odi|profile::FM11g_Odi>>

Oracle Data Integrator Standalone 11g-related problems

=item o B<L<FM11g_OraclePortal|profile::FM11g_OraclePortal>>

Oracle Portal 11g-related problems

=item o B<L<FM11g_PFRD|profile::FM11g_PFRD>>

Oracle Portal, Forms, Reports, and Discoverer 11g-related problems

=item o B<L<FM11g_Soa|profile::FM11g_Soa>>

Oracle SOA Suite 11g-related problems

=item o B<L<FM11g_WebTier|profile::FM11g_WebTier>>

Oracle Fusion Middleware 11g Web Tier-related problems

=item o B<L<FM11g_WlsBi|profile::FM11g_WlsBi>>

Oracle Business Intelligence Enterprise Edition 11g with Oracle WebLogic
Server-related problems

=item o B<L<FM11g_WlsFormsReports|profile::FM11g_WlsFormsReports>>

Oracle Forms/Reports 11g with Oracle WebLogic Server-related problems

=item o B<L<FM11g_WlsIdentity|profile::FM11g_WlsIdentity>>

Oracle Identity Management 11g with Oracle WebLogic Server-related problems

=item o B<L<FM11g_WlsOdi|profile::FM11g_WlsOdi>>

Oracle Data Integrator Suite 11g-related problems

=item o B<L<FM11g_WlsOraclePortal|profile::FM11g_WlsOraclePortal>>

Oracle Portal 11g with Oracle WebLogic Server-related problems

=item o B<L<FM11g_WlsPFRD|profile::FM11g_WlsPFRD>>

Oracle Portal, Forms, Reports, and Discoverer 11g with Oracle WebLogic
Server-related problems

=item o B<L<FM11g_WlsWebTier|profile::FM11g_WlsWebTier>>

Oracle Fusion Middleware 11g Web Tier with Oracle WebLogic Server problems

=item o B<L<FusionApps|profile::FusionApps>>

Oracle Fusion Applications-related problems

=item o B<L<GoldenGate|profile::GoldenGate>>

Oracle GoldenGate-related problems

=item o B<L<GridControl10g|profile::GridControl10g>>

Grid Control 10g-related problems

=item o B<L<GridControl11g|profile::GridControl11g>>

Grid Control 11g-related problems

=item o B<L<HFM_FullRun|profile::HFM_FullRun>>

Oracle Hyperion Financial Management-related problems

=item o B<L<Hyperion1112_EPM|profile::Hyperion1112_EPM>>

Oracle Enterprise Performance Management System 11.1.2.x-related problems

=item o B<L<Hyperion1112_EPMA|profile::Hyperion1112_EPMA>>

Oracle Enterprise Performance Management Architect 11.1.2.x-related problems

=item o B<L<Hyperion1112_ESS|profile::Hyperion1112_ESS>>

Oracle Essbase 11.1.2.x-related problems

=item o B<L<Hyperion1112_FCM|profile::Hyperion1112_FCM>>

Oracle Hyperion Financial Close Management 11.1.2.x-related problems

=item o B<L<Hyperion1112_HCM|profile::Hyperion1112_HCM>>

Oracle Hyperion Calculation Manager 11.1.2.x-related problems

=item o B<L<Hyperion1112_HDRM|profile::Hyperion1112_HDRM>>

Oracle Hyperion Data Relationship Management 11.1.2.x-related problems

=item o B<L<Hyperion1112_HFM|profile::Hyperion1112_HFM>>

Oracle Hyperion Financial Management 11.1.2.x-related problems

=item o B<L<Hyperion1112_HFR|profile::Hyperion1112_HFR>>

Oracle Hyperion Financial Reporting 11.1.2.x-related problems

=item o B<L<Hyperion1112_HIR|profile::Hyperion1112_HIR>>

Oracle Hyperion Interactive Reporting 11.1.2.x-related problems

=item o B<L<Hyperion1112_HPL|profile::Hyperion1112_HPL>>

Oracle Hyperion Planning 11.1.2.x-related problems

=item o B<L<Hyperion1112_HPSV|profile::Hyperion1112_HPSV>>

Oracle Hyperion Provider Services 11.1.2.x-related problems

=item o B<L<Hyperion1112_HSS|profile::Hyperion1112_HSS>>

Oracle Hyperion Shared Services 11.1.2.x-related problems

=item o B<L<Hyperion1112_HSV|profile::Hyperion1112_HSV>>

Oracle Hyperion Smart View 11.1.2.x-related problems

=item o B<L<Hyperion1112_PR|profile::Hyperion1112_PR>>

Oracle Hyperion SQR Production Reporting 11.1.2.x-related problems

=item o B<L<Hyperion_DRM|profile::Hyperion_DRM>>

Oracle Hyperion Data Relationship Management-related problems

=item o B<L<InterMedia|profile::InterMedia>>

Oracle interMedia-related problems

=item o B<L<IpmWls11g|profile::IpmWls11g>>

Oracle Imaging and Process Management 11g-related problems

=item o B<L<Linux|profile::Linux>>

Linux-related problems

=item o B<L<LinuxPerf|profile::LinuxPerf>>

Linux performance problems

=item o B<L<Maa_Assessment|profile::Maa_Assessment>>

Maximum Availability Architecture assessment collections

=item o B<L<Maa_Exa_Assessment|profile::Maa_Exa_Assessment>>

Maximum Availability Architecture with Exadata assessment collections

=item o B<L<Multimedia|profile::Multimedia>>

Oracle Multimedia-related problems

=item o B<L<MySQLCluster|profile::MySQLCluster>>

Oracle MySQL Cluster-related problems

=item o B<L<MySQLDatabase|profile::MySQLDatabase>>

Oracle MySQL Server-related problems

=item o B<L<OSMonitor|profile::OSMonitor>>

Operating system performance sampling

=item o B<L<OVMManager|profile::OVMManager>>

Oracle VM Manager-related problems

=item o B<L<Pda9i|profile::Pda9i>>

Oracle Portal 9i-related problems

=item o B<L<Pda10g|profile::Pda10g>>

Oracle Portal 10g-related problems

=item o B<L<Pda11g|profile::Pda11g>>

Oracle Portal 11-related problems

=item o B<L<PeopleSoft_Appl|profile::PeopleSoft_Appl>>

PeopleSoft application server assessment collections

=item o B<L<PeopleSoft_DB|profile::PeopleSoft_DB>>

PeopleSoft Oracle Database tier assessment collections

=item o B<L<PeopleSoft_Sched|profile::PeopleSoft_Sched>>

PeopleSoft process scheduler assessment collections

=item o B<L<PeopleSoft_Web|profile::PeopleSoft_Web>>

PeopleSoft Web application server assessment collections

=item o B<L<Rac|profile::Rac>>

Real Application Cluster-related problems

=item o B<L<Rac_AdvancedAsm|profile::Rac_AdvancedAsm>>

Cluster and ASM-related problems (ASM advanced mode)

=item o B<L<Rac_Asm|profile::Rac_Asm>>

Cluster and ASM-related problems

=item o B<L<Rac_Assessment|profile::Rac_Assessment>>

Real Application Cluster assessment collections

=item o B<L<Rac_Perf|profile::Rac_Perf>>

Cluster performance problems

=item o B<L<Retail|profile::Retail>>

Oracle Retail-related problems

=item o B<L<Security|profile::Security>>

Filter sensitive information from the reports

=item o B<L<Siebel|profile::Siebel>>

Siebel-related problems

=item o B<L<Siebel_DB|profile::Siebel_DB>>

Siebel with Oracle Database-related problems

=item o B<L<StorageTekTape|profile::StorageTekTape>>

StorageTek Tape Analytics-related problems

=item o B<L<SupportInformer70|profile::SupportInformer70>>

Oracle Communications Billing and Revenue Management 7.0-related problems

=item o B<L<SupportInformer72|profile::SupportInformer72>>

Oracle Communications Billing and Revenue Management 7.2-related problems

=item o B<L<SupportInformer73|profile::SupportInformer73>>

Oracle Communications Billing and Revenue Management 7.3-related problems

=item o B<L<SupportInformer74|profile::SupportInformer74>>

Oracle Communications Billing and Revenue Management 7.4-related problems

=item o B<L<SupportInformer75|profile::SupportInformer75>>

Oracle Communications Billing and Revenue Management 7.5-related problems

=item o B<L<TimesTen|profile::TimesTen>>

Oracle TimesTen-related problems

=item o B<L<TopLink10g|profile::TopLink10g>>

Oracle TopLink 10g-related problems

=item o B<L<Tuxedo|profile::Tuxedo>>

Oracle Tuxedo-related problems

=item o B<L<UcmWls11g|profile::UcmWls11g>>

Oracle Universal Content Management 11g-related problems

=item o B<L<UoaWls11g|profile::UoaWls11g>>

Oracle Universal Online Archive 11g-related problems

=item o B<L<WarehouseBuilder|profile::WarehouseBuilder>>

Oracle Warehouse Builder-related problems

=item o B<L<WebCenter10g|profile::WebCenter10g>>

Oracle WebCenter 10g-related problems

=item o B<L<WebCenter11g|profile::WebCenter11g>>

Oracle WebCenter 11g-related problems

=item o B<L<WebCenterContent10g|profile::WebCenterContent10g>>

Oracle WebCenter 10g with Oracle Content Services-related problems

=item o B<L<WebLogicPortal|profile::WebLogicPortal>>

Oracle WebLogic Portal-related problems

=item o B<L<WebLogicServer|profile::WebLogicServer>>

Oracle WebLogic Server-related problems

=item o B<L<WebSphere|profile::WebSphere>>

IBM WebSphere Application Server-related problems

=back

=head1 COPYRIGHT NOTICE

Copyright (c) 2002, 2012, Oracle and/or its affiliates. All rights reserved.

=head1 TRADEMARK NOTICE

Oracle and Java are registered trademarks of Oracle and/or its
affiliates. Other names may be trademarks of their respective owners.

=cut
