--    Copyright (c) 2005 BEA Systems, Inc.
--    All rights reserved
--
--    THIS IS UNPUBLISHED PROPRIETARY
--    SOURCE CODE OF BEA Systems, Inc.
--    The copyright notice above does not
--    evidence any actual or intended
--    publication of such source code.


-- WLI_QS_REPORT_ATTRIBUTE

CREATE TABLE WLI_QS_REPORT_ATTRIBUTE (
	MSG_GUID 		VARCHAR(64) 	NOT NULL,
	DB_TIMESTAMP 		TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
	LOCALHOST_TIMESTAMP 	TIMESTAMP 	NOT NULL,
	HOST_NAME 		VARCHAR(50) 	NOT NULL,
	STATE           VARCHAR(8)      NOT NULL,
	NODE 		    VARCHAR(128),
	PIPELINE_NAME 		VARCHAR(128),
	STAGE_NAME 		VARCHAR(128),
	INBOUND_SERVICE_NAME 	VARCHAR(256) 	NOT NULL,
	INBOUND_SERVICE_URI 	VARCHAR(128) 	NOT NULL,	
	INBOUND_OPERATION 	VARCHAR(64),
	OUTBOUND_SERVICE_NAME 	VARCHAR(256),
	OUTBOUND_SERVICE_URI 	VARCHAR(256),
	OUTBOUND_OPERATION 	VARCHAR(64),
	MSG_LABELS 		VARCHAR(2048),
	ERROR_CODE 		VARCHAR(64),
	ERROR_REASON 		VARCHAR(1024),
	ERROR_DETAILS 		VARCHAR(2048),
  CONSTRAINT PK_WLI_QS_REPORT_ATTRIBUTE PRIMARY KEY(MSG_GUID)
);


CREATE INDEX IX_WLI_QS_REPORT_ATTRIBUTE_DM ON WLI_QS_REPORT_ATTRIBUTE(
	DB_TIMESTAMP, MSG_LABELS );

CREATE INDEX IX_WLI_QS_REPORT_ATTRIBUTE_IED ON WLI_QS_REPORT_ATTRIBUTE(
	INBOUND_SERVICE_NAME, ERROR_CODE, DB_TIMESTAMP);



-- WLI_QS_REPORT_DATA

CREATE TABLE WLI_QS_REPORT_DATA(
	MSG_GUID 		VARCHAR(64) 	NOT NULL,
        DATA_TYPE	    	SMALLINT,
        ENCODING		VARCHAR(24),
        DATA_VALUE  		BLOB(10000000),
     CONSTRAINT FK_WLI_QS_REPORT_DATA FOREIGN KEY(MSG_GUID)
	  REFERENCES WLI_QS_REPORT_ATTRIBUTE(MSG_GUID) ON DELETE CASCADE
);


CREATE UNIQUE INDEX IX_WLI_QS_REPORT_DATA ON WLI_QS_REPORT_DATA(MSG_GUID);


